### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by mtailanian** [rlrosa/uquad#10]
Primero hacer andar el GPS en la PC y dsp probarlo en la BB

**Comment by rlrosa** [comment]
parece que con el gpsd pudieron hacerlo andar en la compu
yo pude instalarlo en la beagle haciendo

<pre><code>opkg install gpsd</code></pre>


estuvimos hablando con el mati, capaz no vale la pena usar la api, sino directamente leer datos crudos del /dev/ttyUSB#
creo que vale la pena mirar un poco lo que viene con gpsd, a ver si hay algo que nos simplifique la vida.
si usamos directamente el /dev/ttyUSB\* entonces vamos a tener que implementar funciones que parseen lo que se lee de ahí, y se queden con lo que nos interesa
capaz ya viene algo que podés hacer
gps_dame_donde_estoy()
y te hace feliz

siempre está la opción de usar la api, y compilar el código nosotros (yo lo hice, no es dificil. está como submodulo a nuestro proyecto en git (acá hay un poco de info sobre [submodules en git](http://progit.org/book/ch6-6.html)

alguien le mete a esto del gps?
(el q se ofrezca se puede asignar el issue)

**Comment by mtailanian** [comment]
La idea era que el Pater hiciera el primer intento. Ayer hablamos de eso justo. Le asigno a él y en todo caso yo me sumo dsp...

Toy de acuerdo q es mejor no usar la api y aparte debe ser hasta más fácil leer del puerto con un `cat` pelado...

Salute!

**Comment by rlrosa** [comment]
2011/10/19 MatiTaila
reply@reply.github.com:

> La idea era que el Pater hiciera el primer intento. Ayer hablamos de eso justo. Le asigno a él y en todo caso yo me sumo dsp...
> 
> Toy de acuerdo q es mejor no usar la api y aparte debe ser hasta más fácil leer del puerto con un `cat` pelado...

yo voto por _no_ arrancar por un cat
desde c no vas a poder hacer cat, vas a tener que leer hasta _algo_
que te indique q ya está, o _x_ cantidad de caracteres
si hay una función en la api que es leer_gps() y te devuelve un
puntero a algo tipo
<pre><code>struct datos_gps{
  int num_satelites;
  int latitud;
  int longitud;
};
</pre></code>
entonces nos ahorramos mucho trabajo.

yo arrancaría viendo si el gpsd o alguno de los programas que trae te
ofrece algo de este tipo, sino revisaría la API a ver si la API tiene
algo así.
si la api tiene algo así entonces en mi opinión va a ser más fácil
usarla que arrancar de cero.

salú!

> Salute!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/10#issuecomment-2454234

## 

Rodrigo.

**Comment by spaternain** [comment]
Cuando dicen la api a que se refieren???

**Comment by spaternain** [comment]
El gpsd tiene mucha cosa interesante.... voy a hacer una especie de recorte y pegue de las cosas que precisamos y voy a tirar lo que no

**Comment by rlrosa** [comment]
una API es una interfaz con algo. una libreria x ejemplo.
te da ciertas funciones, y no tenés xq (en teoría) preocuparte por como están hechas.

la lib que ofrece gpsd es esta:
http://catb.org/gpsd/libgps.html

capaz se puede sacar info de acá http://catb.org/gpsd/protocol-transition.html

la movida es tener el daemon corriendo, que se encarga de darse cuenta que conectaste el gps, y ir a buscar datos nuevos, etc, y usar esa lib para comunicarse con el daemon desde nuestro loop.

no hace falta compilar cosas nosotros para hacer esto, solamente hace falta incluir los headers (*.h) de la lib y dsp linkear con la lib
si quieren puedo ver de arrancar esto así nomás, cosa de safar la parte de hacer un prog que use la lib, y dsp les dejo la parte de hacer un prog que use la lib de una manera util

**Comment by spaternain** [comment]
No, no.... dejalo así que yo le quiero meter.... a no ser que ya no tengas nada más para hacer.....

**Comment by spaternain** [comment]
Estuve mirando un poco el gpsd. Uno de los archivos que trae es el cgps que es un cliente(presenta los datos lindos??? o eso entiendo yo...) Tiene una función que esta buena que es update_gps_panel. No he podido entender bien quien se encarga de modificar los datos que se reciben, pero esa función parece funcionar como si ya tuviera eso resuelto. Por lo tanto se puede imitar esa función pa obtener posicion,etc....

No se, mirenlo a ver si no estoy enjacando mucha fruta

**Comment by spaternain** [comment]
La verdad que me paso un poco el agua con esto del gps. Todavía no pude entender bien quien hace que. El otro día hablé un rato con el rela y pensé que estaba todo más claro, pero no....

Por lo que entiendo el gpsd es un programita que puede quedar corriendo en paralelo mientras yo hago otras cosas. La biblioteca que tengo agregando el "gps.h" me da funciones para comunicarme con el gpsd. 

Si es así, habría que volver a probar el script que había hecho porque nunca habíamos corrido el gpsd.

La biblioteca tiene una función que se llama gps_data() que devuelve los datos del gps : satélites, latitud, longitud,etc
Esto es super útil ya que nos ahorra muchisimo trabajo.

El tema es que no se como avisarle al loop de control que tengo un nuevo dato. Eso no lo pude encontrar en el código.

**Comment by rlrosa** [comment]
el finde puedo mirar un poco, dsp te skype y vemo entre los dos a ver q sale
te pa?

2011/10/28 spaternain
reply@reply.github.com:

> La verdad que me paso un poco el agua con esto del gps. Todavía no pude entender bien quien hace que. El otro día hablé un rato con el rela y pensé que estaba todo más claro, pero no....
> 
> Por lo que entiendo el gpsd es un programita que puede quedar corriendo en paralelo mientras yo hago otras cosas. La biblioteca que tengo agregando el "gps.h" me da funciones para comunicarme con el gpsd.
> 
> Si es así, habría que volver a probar el script que había hecho porque nunca habíamos corrido el gpsd.
> 
> La biblioteca tiene una función que se llama gps_data() que devuelve los datos del gps : satélites, latitud, longitud,etc
> Esto es super útil ya que nos ahorra muchisimo trabajo.
> 
> El tema es que no se como avisarle al loop de control que tengo un nuevo dato. Eso no lo pude encontrar en el código.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/10#issuecomment-2557033

## 

Rodrigo.

**Comment by spaternain** [comment]
Dale, 

lo miramos el domingo. El sábado no creo que pueda xq nos vamos a juntar a ver si podemos sniffear algo...

**Comment by spaternain** [comment]
Gente que encara cocinando kernels:

No se si vieron la wiki del gps, pero agregue algunas cosas y aparentemente yo creo que el gpsd quedó funcionando. Habría que compilar el cgps o hacer un cat en algún momento que tenga señal para ver que efectivamente anda todo bien.

Lo que tiene es que es un embole así como está porque hay que agregar un módulo cada vez que prendo la beagle. Sin embargo acá: http://koti.mbnet.fi/lonnberg/pl2303x.html hay un parche que supuestamente hace eso.

Si pueden peguenle una miradita

**Comment by rlrosa** [comment]
bueno, no tuve suerte con la beagle todavia.
reconoce el gps, pero no arranca a leer.
capaz es lo del http://koti.mbnet.fi/lonnberg/pl2303x.html, pero me está complicando algo del bitbake que no me deja cocinar en paz, y aparte el post ese es del 2005, y el patch no aplica. me parece que ese post quedó obsoleto, lo cambios del patch ya están metido en el código que viene por defecto.
igual no estoy seguro.

lo que hay ahora es un programa que viene con el paquete _gpsd-clients_, lo corrés haciendo:<pre><code>gpxlogger -f log_file_name
</code></pre>

y te va tirando data al archivo que le pasaste.

creo que eso serviría xa las pruebas que pinta hacer.
por ahora sería con una laptop, xq la beagle no quiere todavía.

**Comment by rlrosa** [comment]
esto es lo que saqué de la data d hoy:
el error entre el nuestro y el pulenta es más o menos de la misma pinta que entre las dos tiradas de datos del nuestro, así que asumo que debe andar por los 4-8m máx, igual que el error entre nuestras tiras.

<img src="http://i43.tinypic.com/hx6ltu.png" alt="some_text"/>

**Comment by rlrosa** [comment]
compramo otro gps (igual)?
fede creo que arranca xa acá el 24, sino los padres de juan vienen dsp de fin de año.
capaz mejor pedirle a los padres de juan, así no le pedimo otra cosa + a fede

**Comment by mtailanian** [comment]
Por qué otro gps?
y por qué igual?
en todo caso comprariamos uno mejor no?

**Comment by rlrosa** [comment]
On Tue, Dec 20, 2011 at 12:32 PM, MatiTaila
reply@reply.github.com
wrote:

> Por qué otro gps?
> y por qué igual?

por lo mismo que tenemos 2 beagles
por si se nos cae del techo hoy.

> en todo caso comprariamos uno mejor no?

puede ser, pero yo compraría 2

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/10#issuecomment-3219413

## 

Rodrigo.

**Comment by rlrosa** [comment]
capaz ta bueno esperar un rato, ver como se porta este, y pedimo xa la
vuelta de los padres de juan
ahí no daría xa saber si nos gusta este

On Tue, Dec 20, 2011 at 12:34 PM, Rodrigo Rosa rodrigorosa.lg@gmail.com wrote:

> On Tue, Dec 20, 2011 at 12:32 PM, MatiTaila
> reply@reply.github.com
> wrote:
> 
> > Por qué otro gps?
> > y por qué igual?
> 
> por lo mismo que tenemos 2 beagles
> por si se nos cae del techo hoy.
> 
> > en todo caso comprariamos uno mejor no?
> 
> puede ser, pero yo compraría 2
> 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/rlrosa/uquad/issues/10#issuecomment-3219413
> 
> ## 
> 
> Rodrigo.

## 

Rodrigo.

**Comment by mtailanian** [comment]
> por lo mismo que tenemos 2 beagles

¿Por si te vas un añito más a alguna parte del mundo? :P

**Comment by rlrosa** [comment]
2011/12/20 MatiTaila
reply@reply.github.com:

> > por lo mismo que tenemos 2 beagles
> > ¿Por si te vas un añito más a alguna parte del mundo? :P
- bien xq me volví y me traje mi gran habilidad de ser pera, aprendí a
  quemar de todo un poco jej

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/10#issuecomment-3219532

## 

Rodrigo.

**Comment by mtailanian** [comment]
Si, nosotros tmb andamo rico pa quemar, sino preguntale al primer quad!
es lo nuestro, sin duda

**Comment by rlrosa** [comment]
bueno, parece que el gps anda con la beagle. un cat muestra lecturas.

todavía no estoy seguro sobre el gpsd, ta medio rompe bolas.
lo pude cross-compilar, algo es algo.
no se si es el daemon (gpsd) q no anda, o el cliente (gpxlogger).

voy a probar con un programita sencillo hecho por mi, a ver q tal. si eso no anda entonces es culpa del gpsd.

**Comment by rlrosa** [comment]
armé un "informe" sobre lo del GPS del otro dia.
está en: https://github.com/rlrosa/uquad/blob/master/src/gps/data/21_12_2011_logs/informe/uquad_gps_polygono_21_12_2011.tex

no da un rectángulo ni a palo.
puedo estar haciendo algo mal, pero no creo.

ahora toca pensar que hacer con esto.
voy a ver si se me ocurre/encuentro alguna forma de sacarle el jugo a la info que tira el GPS, sino habrá que valerse de otros sensores.

**Comment by mtailanian** [comment]
Ta bueno el informe!
taría bueno juntarlo con lo q ya tenía hecho del experimento del GPS....
está en la carpeta Organización/tests/GPS, o algo así

Lo q estaba hecho es como una guía de lo q había q hacer... La idea era completar abajo con los resultados.. no hacer otro... Además falta agregar lo del polígono que no estaba...
movés eso q hiciste? así queda más ordenado?
capaz organización no es el mejor nombre para la carpeta, pero se cambia... lo q si está bueno son los informes de los tests que ya había hecho...

**Comment by rlrosa** [comment]
2011/12/25 MatiTaila
reply@reply.github.com:

> Ta bueno el informe!
> taría bueno juntarlo con lo q ya tenía hecho del experimento del GPS....
> está en la carpeta Organización/tests/GPS, o algo así
> 
> Lo q estaba hecho es como una guía de lo q había q hacer... La idea era completar abajo con los resultados.. no hacer otro... Además falta agregar lo del polígono que no estaba...
> movés eso q hiciste? así queda más ordenado?
> capaz organización no es el mejor nombre para la carpeta, pero se cambia... lo q si está bueno son los informes de los tests que ya había hecho...

ok.
yo nunca había leído eso, no sabía que existía.
dsp lo muevo.
talué!

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/10#issuecomment-3271763

## 

Rodrigo.

**Comment by mtailanian** [comment]
buenazo

**Comment by spaternain** [comment]
Se animan a mandar el PDF que estoy en el laburo y no tengo para compliar?

**Comment by spaternain** [comment]
Me parece que está muy bien! Les parece mandarselo a Canetti?

Saludos

**Comment by rlrosa** [comment]
por mi si, a ver q tienen xa decir.

On Mon, Dec 26, 2011 at 12:30 PM, spaternain
reply@reply.github.com
wrote:

> Me parece que está muy bien! Les parece mandarselo a Canetti?
> 
> Saludos
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/10#issuecomment-3274810

## 

Rodrigo.

**Comment by rlrosa** [comment]
voy a modificar el test del error diff del GPS, y adecuarlo al test q hice. ok?

falta procesar lo del error absoluto. tengo todo xa hacerlo si la info
del GPS con correción diferencial la tomamos como referencia (asumimos
q es correcta)

por mi mandale al canetti, si querés aguantá que hago lo del absoluto

2011/12/26 Rodrigo Rosa rodrigorosa.lg@gmail.com:

> por mi si, a ver q tienen xa decir.
> 
> On Mon, Dec 26, 2011 at 12:30 PM, spaternain
> reply@reply.github.com
> wrote:
> 
> > Me parece que está muy bien! Les parece mandarselo a Canetti?
> > 
> > Saludos
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/rlrosa/uquad/issues/10#issuecomment-3274810
> 
> ## 
> 
> Rodrigo.

## 

Rodrigo.

**Comment by spaternain** [comment]
Na... aguanto tranqui... mejor mandarle todo completo. Aunque lo importante ya vimos que no anda muy bien

**Comment by spaternain** [comment]
Pregunta: Cuantos satélites veías cuando hiciste la prueba?

**Comment by rlrosa** [comment]
entre 7 y 9

2011/12/26 spaternain
reply@reply.github.com:

> Pregunta: Cuantos satélites veías cuando hiciste la prueba?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/10#issuecomment-3275588

## 

Rodrigo.

**Comment by spaternain** [comment]
Creo que da para ponerlo en el informe

**Comment by spaternain** [comment]
Ta pronto el informe?? Hay que mandarselo a Canetti, estaría bien terminar el año mandandole eso

**Comment by rlrosa** [comment]
todava no, pero este ao lo termino

On Dec 28, 2011 11:29 AM, "spaternain" <
reply@reply.github.com>
wrote:

**Comment by rlrosa** [comment]
bueno, creo que quedó algo en https://github.com/rlrosa/uquad/tree/master/tests/gps

falta lo que hicimos atrás de la fac, pero igual a canetti no pareció gustarle.
estuve viendo con el mapa de la imm pero se las pisa, voy a ver si puedo sacarle algo útil dsp.

**Comment by rlrosa** [comment]
estuve hablando con diego, parece que tenemos que tener entre 4 y 5 GPSs, para encontrar el camino + corto.
tmb tenemos que usar los postes de luz para recargar la batería del quad, pero usando un sistema de tarjetas prepagas, xq si usamos monedas, entonces seguro nos roban todo.

**Comment by spaternain** [comment]
WTF???

**Comment by rlrosa** [comment]
alguien entendió lo del mínimos cuadrados q es "super sencillo" q dijo el canetti?

armé el rectángulo, y medí las distancias de c/punto a c/otro punto, con la cinta métrica.
no todas miden exactamente lo q deberían (como era d esperarse)

según entendí, la movida ahora es agarrar todas los lados/diagonales, y armar un polígono chueco.

si llamo p1 al punto 1, p2 al 2, etc, de coordenadas [x1,y1], [x2,y2], etc, y d12 a la recta q una p1 con p2 (medida con metro) entonces me quedaría:

norma(p1 - p2) = d12
norma(p1 - p4) = d14
norma(p1 - p5) = d15
...
norma(p4 - p5) = d45
etc

pero cada eq de esas queda fea, con un x_1, x_2, y_1 e y_2 al cuadrado, y terminos cruzados (x_1*x_2, etc).
alguna idea?

los datos del gps no me hacen muy feliz. me voy a la fac a tomar algunos más, a ver si x lo menos es aleatorio.
promediando los datos en cada punto, queda (links a fotitos):
- [10 min por punto - orientacion 1](http://i43.tinypic.com/260e6hc.png)
- [2 min por punto - o1rientacion (120grad respecto de 1)](http://i40.tinypic.com/2wri8o4.png)
- [2 min por punto - orientacion 2 (60grad respecto de 1)](http://i42.tinypic.com/2q33ep3.png)

quiero repetir orientaciones a ver si se repite el error, etc.
en algunos puntos da tipo horrible comparado con otros. voy a repetir a ver si se repite.

**Comment by spaternain** [comment]
Tenés que resolver un problema de mínimos cuadrados no lineal. Yo para la calibración del acelerómetro estoy trancado en lo mismo. Si aprendo algo te aviso.

**Comment by mtailanian** [comment]
lsqnonlin

Salió con eso!
y dió rico. el pater les cuenta dsp :-)

**Comment by rlrosa** [comment]
quedó una primera versión de la segunda versión del informe que tendría que haber terminado cuando era joven, hace un par de semanas.
falta el escalón todavía. es medio indep de lo demás, así si tienen un ratito pueden irlo mirando así como está a ver q les parece.

**Comment by rlrosa** [comment]
sobre la respuesta al escalón, dsp le preguntamos al tio a ver si le interesa mucho.
yo creo que no vale mucho le pena (me embola)

para hacer algo útil tendríamos que tener algo donde se pueda estimar los parámetros interesantes de la resp escalón (sobretiro, t de subida, etc) y para hacer eso con algo que tiene  un error de 5m tendríamos que correr como 100m o más, no pinta me pinta hacer eso con la laptop... capaz el martes cuando tengamos el quad volando podemos probar.

**Comment by spaternain** [comment]
Acabo de leer el informe. Me parece que está bien. Tiene algunas cosas de redacción que no están como para una versión final, pero ta. No voy a romper las bolas con eso. 

Me parece muy importante la conclusión que hace referencia a un sensor de presión. Hoy hablando con el mati me dijo lo mismo. No se si ya lo habían comentado, pero estoy de acuerdo y deberíamos movernos para conseguir uno. 

No me gusta mucho que el tiempo necesario de medidas para tener una buena estimación sea de 2 minutos. Pero ta, si es lo que hay es lo que hay. No se como vamos a luchar contra eso... pero bueno, en fin....

Por último. Habría que empezar a pensar (por más que el giróscopo no está calibrado todavía) como vamos a hacer la integración de los sensores. 

Por un lado, está el GPS que nos dá un error de un par de metros con medidas de 2 minutos. Por otra parte los errores del acelerómetro son menores a 0.1m^(-2) con un 95% de probabilidad. Por más que parece bastante bueno hay que ver que en dos minutos el error que se genera es de 720 metros. ABERRANTE. Con el acelerómetro es muy fácil graficar el error en función del tiempo. Con el GPS no se si hay una relación tan directa. Probablemente lo mejor sea estudiar los logs que ya tomamos y caracterizar el error en función del tiempo de medidas. Donde se corten las rectas es el mejor tiempo para usar el GPS no? 

Perdón por lo extenso del mail

**Comment by mtailanian** [comment]
cierro aca
