### ISSUE TITLE
informe del grupo sobre el tutor

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#11]
eu opinen, cambien lo que crean.
puse mi opinión para tener algo.
uds sabe mucho más que yo sobre el tutor, así que cambien nomás.

es xa ya esto...
yo subí lo mio nomás.

[eval tutor](https://github.com/rlrosa/uquad/blob/master/eval/Evaluacion_del_grupo_sobre_el_Tutor.txt)

**Comment by spaternain** [comment]
Pa mi que esta bien.... yo no hice el personal.... recien ahora lo miro... como es la movida??? hay que puntuarse de 1 a 5 siendo 5 soy un cra y 1 una pija???

Saludos

**Comment by rlrosa** [comment]
yo no vi nda de puntos, escribí ahí unas cosas

2011/10/3 spaternain
reply@reply.github.com:

> Pa mi que esta bien.... yo no hice el personal.... recien ahora lo miro... como es la movida??? hay que puntuarse de 1 a 5 siendo 5 soy un cra y 1 una pija???
> 
> Saludos
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/11#issuecomment-2270847

## 

Rodrigo.

**Comment by mtailanian** [comment]
hay 2 cosas q hacer. 
1 es grupal que es la evaluación del tutor
La otra es individual y cada uno pone puntajes a distintas cosas, evaluando a los compañeros de proy,
En la página de proy está todo.

Rela el matute escribio otra de la que habías escrito vos, nos la mostró y ya la entregamos. fijate en la pág cualquier cosa

**Comment by rlrosa** [comment]
la grupal me la hice por tener algo
creo que uds tienen la opinión posta sobre esa.
doy x listo ya q entregamos.

**Comment by mtailanian** [comment]
Igual tenés que hacer la otra tmb...

**Comment by rlrosa** [comment]
yo ya mande
