### ISSUE TITLE
src

### ISSUE THREAD

**Issue by spaternain** [rlrosa/uquad#12]
Rela,

Te animas a comentar un poco el código que has hecho o por lo menos dar una explicacion general de que es lo que hay en cada lugar. Ta medio crudo pa arrancar de cero a entender todo lo que has hecho.

Tiene pinta de que está muy rico XD

**Comment by rlrosa** [comment]
para entrarle al código hay q empezar por el README en src/
ahí explica como hacerlo andar.

dsp de tenerlo todo compilado se puede probar cosas desde src/build/test/*
ahi es donde van a parar un par de programas de prueba, en particular
imu_comm_test, que sirve xa hacer algo parecido a lo que hace el
imu_display, solo que sin colores ni display ni nada cheto

estoy viendo que onda con los datos que me tira el imu, a ver cuanto
hace falta calibrar para que funcione
a medida que le vayan entrando me preguntan
traté de comentar bastante el código

salú!

2011/10/18 spaternain
reply@reply.github.com:

> Rela,
> 
> Te animas a comentar un poco el código que has hecho o por lo menos dar una explicacion general de que es lo que hay en cada lugar. Ta medio crudo pa arrancar de cero a entender todo lo que has hecho.
> 
> Tiene pinta de que está muy rico XD
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/12

## 

Rodrigo.

**Comment by rlrosa** [comment]
la parte del log me faltaron comentarios, dsp agrego.
lo único que hace es generarte un string q tiene fecha y hora, sirve xa usar de nombre a los logs y evitar repetir nombres

dsp la otra es una boludez.
dsp comento
(te borré el comentario xq lo pusiste en el issue equivocado :) )

**Comment by rlrosa** [comment]
abran si se trancan en algo
