### ISSUE TITLE
Generador de Rutas

### ISSUE THREAD

**Issue by spaternain** [rlrosa/uquad#13]
Gente, 

Encontré un papper no se si muy interesante pero me gusto mucho el capítulo 2 donde el loco habla en general de los encares desarrollados por otros botijas para determinar la ruta del quad. El link es este:

http://www.cs.uni-salzburg.at/~ckrainer/jnavigator-20090917-final.pdf

Yo todavía no tengo claro que mierda es lo que queremos que el quad haga, pero acá hay algunas posibilidades interesantes algunas más fáciles que otras... desde una trayectoría que sean rectas hasta un sistema en varias capas para buscar cosas, investigar un entorno desconocido, y algun otro pire... hay uno que hace interactuar dos quads... canetti quería hacer algo de esto... 

No sé... peguenle una miradita si pueden y lo charlamos

**Comment by spaternain** [comment]
Este papper está muy interesante

http://robotics.eecs.berkeley.edu/~sastry/pubs/PDFs%20of%20Pubs2000-2005/Pdfs%20of%20Misc.Others/Kim,H.Jin/KimFlightControlSystem2003.pdf

**Comment by mtailanian** [comment]
Que onda con esto? cierro?
habíamos dicho de dejarlo en stand by....

**Comment by spaternain** [comment]
Este también
