### ISSUE TITLE
imu - interpretación de los datos

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#14]
el codigo del imu lee, pero falta masticar bien
- estimar los params de un modelo <code>ax + b</code>.
  - el offset <code>b</code> se calcula haciendo la media de los datos con el imu quieto.
  - la ganancia <code>a</code> no se estima (por ahora). habría que hacer algo experimental para esto:
    - Armar algo que gire a una velocidad angular configurable, <code>w</code>, y razonablemente precisa. ver si el IMU está de acuerdo con la velocidad a la que gira. con un sistema así se podría relevar la respuesta del sensor. conociendo el offset se puede estimar la ganancia

no he buscado como hace la gente xa resolver esto, pero creo que este plan tiene sentido

**Comment by spaternain** [comment]
Esto lo vamos a medir con un tocadisco, es algo que gira a una velocidad constante y tiene que ser prolijo xq sino suena pal culo la música. Con esto podemos medir velocidad de giro en las tres direcciones y aceleración también. 

Salute
