### ISSUE TITLE
beagle-imu: comm & pwr

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#15]
Logré sacar el UART2 de la beagle, y me puse a ver un poquito sobre como conectar a esta gente.
Hay q hacer dos cosas:
- Alimentar a la IMU
- Interconectar RX/TX
# 5v en la beagle

El pin2 del expansion header en la beagle es 5v, y sobre chupar de ahí tenemos esto de la [datasheet de la beagle](https://github.com/rlrosa/uquad/blob/master/datasheets/beagleboard/BBxMSRM_latest.pdf):

> The other rail is the DC_5V. The same restriction exits on this rail as mentioned in the
> USB section. The amount of available power to an expansion board depends on the
> available power from the DC supply or the USB supply from the PC.

O sea q de fiesta, mandamo cable a la IMU y dale q va. Que la IMU chupe del can.
# comm serie

La imu quiere 3.3v-5v para la comm serie, la beagle quiere 1.8. Ahí vamo a tener que meter un shifter.
estuve viendo un [Logic Level Converter](http://www.sparkfun.com/products/8745) que vende sparkfun por USD 2. el [schematic](http://www.sparkfun.com/datasheets/BreakoutBoards/Level-Converter-v10.pdf) es re choto.
mñna le pregunto a roberto donde se encanuta transistores tipo bss138, y me hago uno.
si andan se hacen uno ahí y ya era

**Comment by mtailanian** [comment]
Pa mi la posta es q te compres un par de esas y no te gastes en hacerlo. Son re baratas y no perdés tiempo.
También acordate de comprar las hélices de repuesto!

Nosotros acá nos arreglamos con algo parecido a lo q nos dio el Leo hasta que vuelvas.

**Comment by rlrosa** [comment]
el shipping sale lo mismo que 2 de estos!
jej

hoy pregunto acá, si tienen las cosas hago uno en unos "vector boards"
q es un toque
BB son plaquitas genéricas q vienen xa soldarles cosas arribas

salú!

57d0a798833032c7e0@reply.github.com>:

> Pa mi la posta es q te compres un par de esas y no te gastes en hacerlo. Son re baratas y no perdés tiempo.
> También acordate de comprar las hélices de repuesto!
> 
> Nosotros acá nos arreglamos con algo parecido a lo q nos dio el Leo hasta que vuelvas.

ya probaron?

> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/15#issuecomment-2544864

## 

Rodrigo.

**Comment by mtailanian** [comment]
Hablamos con esa gente de sistemas embebidos y dijeron q no hay chance de hacerlo comprando cosas aca. Así que vamos a comprar uno y capaz que ellos se suman para comprar. Si queres hacerlo porque te gusta hacer plaquitas, hacelo, pero no es necesario. 

La alimentación me parece más fácil sacarla de la Beagle Juice.

**Comment by mtailanian** [comment]
"Logré sacar el UART2 de la beagle"

Que hiciste?

**Comment by rlrosa** [comment]
> Hablamos con esa gente de sistemas embebidos y dijeron q no hay chance de hacerlo comprando cosas aca. Así que vamos a comprar uno y capaz que ellos se suman para comprar. Si queres hacerlo porque te gusta hacer plaquitas, hacelo, pero no es necesario.

compro o compran?
yo hice una, todavía no terminé de conectar como xa probarla.

>  La alimentación me parece más fácil sacarla de la Beagle Juice.

_más fácil_?

> "Logré sacar el UART2 de la beagle"
> Que hiciste?

[Custom-u-boot](https://github.com/rlrosa/uquad/wiki/Custom-u-boot)

**Comment by rlrosa** [comment]
parece que el circuito de sparkfun no funciona si el q escucha en nivel alto tiene pull-ups, y la imu tiene pull ups.
en lugar de llegarle una señal entre 0-3.3 le llega una cagadita que baila entorno a 3.3 (200mV de amplitud)

le saqué R4 y quedó lo mismo, pero entre 0-1.5v
opciones:
1. usar otro shifter, todavía no busqué
2. reprogramar la imu xa que no use los pull ups. la parte de código es fácil, es cambiar 1 bit en la init, lo aburrido es armar una interfaz xa bajar el código a la imu.

la opción de reprogramar suena a patada en las bolas, pero capaz no es mala idea, ya que puede ser necesario hacerle algún cambio dsp.
si hacemo esa interfaz ya nos habilita a cambiar lo que querramos en la imu.

q dicen?

**Comment by mtailanian** [comment]
No se qué tanto queramos cambiar cosas en la imu... 

Me parece mejor buscar otro convertidor de niveles, en sparkfun deben tener algo que ande con la imu... podés llamar ahí rela? Eso es lo más fácil... si no anda eso vemo otro.. que dicen?

Digo de tratar de eludir la reprogramación y la interfaz de la imu... Si no hay nada raro lo único q necesitamos es tocar la calibración... no se, me parece medio laburo al pedo entrar en esa, más q ya estamos bien atrasaditos...

Les parece? llamas?

**Comment by spaternain** [comment]
|parece que el circuito de sparkfun no funciona si el q escucha en nivel alto tiene pull-ups, y la imu tiene pull ups.
|en lugar de llegarle una señal entre 0-3.3 le llega una cagadita que baila entorno a 3.3 (200mV de amplitud)

Esto lo probaste vos o lo leíste por ahí?

|le saqué R4 y quedó lo mismo, pero entre 0-1.5v
Ta raro esto no?

**Comment by rlrosa** [comment]
2011/11/2 spaternain
reply@reply.github.com:

> |parece que el circuito de sparkfun no funciona si el q escucha en nivel alto tiene pull-ups, y la imu tiene pull ups.
> |en lugar de llegarle una señal entre 0-3.3 le llega una cagadita que baila entorno a 3.3 (200mV de amplitud)
> 
> Esto lo probaste vos o lo leíste por ahí?

lo probé
quedaba una cagada bailando arriba

> |le saqué R4 y quedó lo mismo, pero entre 0-1.5v
> Ta raro esto no?

no se, preguntale a alguien q sepa de electrónica, algún ingeniero je

acá hay una caja llena de placas viejas q van a tirar, uno de los
integrados que tiene es un inversor de dos canales
tiene 6 patas:
- 2 entradas, y sus corresp 2 salidas
- vcc y gnd

se banca entradas de 0-7v, y te saca la entrada invertida, entre 0 y vcc
si vcc==3.3
  vin = 0 -> vout = vcc = 3.3
  vin = 1.8 != 0 -> vout = 0

si vcc==1.8
  vin = 0 -> vout = vcc = 1.8
  vin = 1.8 -> vout = 0

el tema es q te invierte la lógica, pero usando 2 de estos en serie lo arreglás.
ayer armé el circuito a ver q onda
mñna lo pruebo.

si anda puedo hacer un par más y llevar, son gratis, pero no es muy
feliz. dsp mando foto xa q vean jej

> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/15#issuecomment-2612288

## 

Rodrigo.

**Comment by rlrosa** [comment]
bueno, anduvo lo del circuito con los dos inversores.
lo inversores en EVO son gratis, son componentes de unas placas q están xa tirar, donantes de órganos
puedo averiguar cuanto cuesta imprimir una placa más razonable que lo que hice, sino armar una como la que hice pero de manera más prolija, un poquito creo que se puede :P
q dicen?

el de sparkfun es barato, pero no anda.
no encontré mucha cosa con placa linda como xa soldar cosas.
hay unos integrados que hacen magia, pero no vienen con placa, o sea que tmb tenemos que hacer placa o hacer magia
yo voto por q las arme yo
si hacer placa es caro las armo así nomás. dps de ver que funca se bañan en silicona y ya no hay riesgo de andar arrancando alambres, o sea que no va a ser algo super sensible que seguro se rompe, va a ser feo nomás.

puse un tres fotos en google xa no ocupar el repo con boludeces je tenemo creo q 2gb nomás.
no me quedó claro que hizo el g+, se supone que les avisó.
link q no se si anda a un [zoom del circuito](https://lh5.googleusercontent.com/-NoD-ATa7xlM/TrI8-ZXlqgI/AAAAAAAAAJE/t49S-h5Ap_Y/h301/Imu-beagle-close.jpg)

**Comment by mtailanian** [comment]
Bien!
Pa mi puede andar

Hacer una placa no es problema. En facultad tenemos 2 maneras:
1. Pedir que nos presten una máquina que imprime circuitos (je)
2. Hacerla en el lab. Los gurises q estan ahí hacen placas todos los días, seguro no les jode que colemos una nuestra...

Pasanos un esquemático o algo y lo hacemos. Yo me encargo si quieren. No creo q tenga componentes muy raros, supongo q se conseguirá todo acá...

Va, si están de acuerdo en usar esto.. ¿Qué es lo q tiene? ¿Solo inversores lógicos?

Otra cosa:
Para la com Beagle-Imu necesitamos 2 de esos no? Uno pal Tx y otro pal Rx. Y necesitamos alimentar uno  con 3.3 y uno con 1.8 no? Es medio incómodo, pero se puede hacer. Si es así en el circuito impreso q vamos a hacer podemos incluir alguna circuitería que baje de 5V a 1.8V y de 5V a 3.3V. Eso es fácil igual. Yo me animo a armar algo completo. 

Lo ideal sería todo en 1 sola placa, que se alimente con 5V. Que tenga 2 reguladores de tensión que arrojen 3.3V y 1.8V. Esos voltajes se usan como Vcc para hacer 2 de los circuitos que dice el rela (que en realidad son 4 porque cada uno son 2 en serie).
Todo eso se puede hacer fácil. Si quieren ya me meto en eso. Lo único que necesito es el esquemático de ese inversor lógico...

**Comment by rlrosa** [comment]
tiene 2 componentes nomás, dsp alambres je
el inversor es un [nc7wz14](www.fairchildsemi.com/ds/NC/NC7WZ14.pdf)

la movida es unir las patitas como [este esquemita](https://plus.google.com/u/0/photos/103530989756129964055/albums/5625751186094991281/5670809687692430850)
si el link no andan busquen en mis fotos en google, en la carpeta donde subí las fotos del circuito
te alcanza para armar con eso?

**Comment by mtailanian** [comment]
Bo, fuimo a Rondeau y resulta que en Uruguay NO HAY INVERSORES.

Una japi.

Igual el Matute se va a Bs. As. con su novia (embarazada de un matutito) el fin de semana que viene. La idea es q los compre ahi...

Por las fotos que vi ya conectaste la imu con la beagle. Anduvo todo bien? pudiste leer lo q tira la imu desde la beagle?

**Comment by rlrosa** [comment]
> Bo, fuimo a Rondeau y resulta que en Uruguay NO HAY INVERSORES.

ta d 10 rondeau, no te dejan gastar plata ;)

tienen alguna forma de leer de la imu?
no hace falta la beagle para probar los sensores
si tienen alguna forma de leer tonce me puedo llevar un montón de acá
me llevo algunas listas, 2 o 3, y aparte un montón de inversores por las dudas.

vo, q onda un matutito?
no se si el estado uruguayo lo permite

> Por las fotos que vi ya conectaste la imu con la beagle. Anduvo todo bien? pudiste leer lo q tira la imu desde la beagle?

sip, y pude.
no probé el imu_comm, pero el cat anda, así q debería andar

**Comment by mtailanian** [comment]
Bien, eso es una buena noticia. Saber q lograste la comm con algo.
Lo de los inversores no me gusta demasiado. Yo había encontrado hace un tiempo un circuito para convertir niveles lógicos usando un MAX3318 (creo q era ese) pero el problema es que acá no había. Hoy lo buscamos de nuevo y corroboramos que efectivamente sirve. Aparte hay otro MAX que tiene pines bidireccionales y puede servir para la comm i2c.

La idea es q el matute se traiga de bsas unos maxes y hagamos todo con eso. Me parece más feliz que 2 inversores en serie. Aparte también tendríamos solución para el i2c que es bidireccional.

que decis? te parece buen plan? (igual mucho no me importa, pero ta... je...)
Como opción B tenemos los inversores que ya sabemos que andan! :-)

**Comment by rlrosa** [comment]
ok

**Comment by mtailanian** [comment]
Igual traete un par armadas y unos inversores de repuesto, never know.....

**Comment by rlrosa** [comment]
esto tiene trabajo por hacer, pero creo que está resuelto.
- Voy a llevar dos circuitos armados, con inversores. Tengo 1 listo y andando, y dos que no pude, estuve como 5-6 horas, es jodido conectar cosas tan chiquititas (hay fotos en g+)
- En la lista de compras van MAX, y llevo inversores de repuesto.

creo que esto se puede cerrar.
