### ISSUE TITLE
Testeo de sensores - IMU

### ISSUE THREAD

**Issue by mtailanian** [rlrosa/uquad#16]
# Evaluación del Drift a largo plazo

La idea es hacer un recorrido con la imu enchufada a la compu (o a la Beagle)  e ir guardando todos los datos que arroja el sensor para luego contrastar con la realidad. Para ello se debe
1. Hacer un código que vaya guardando en un archivo todos los datos que arroja la IMU. 
2. Planear rutas controladas y medibles para contrastar los resultados

**Comment by mtailanian** [comment]
# Calibración

Para esto usamos el tocadiscos. Las ideas que hay hasta ahora son:
1. Ponerlo en el centro del tocadiscos en las 3 posiciones posibles para contrastar velocidades angulares en los 3 ejes.
2. Ponerlo en el borde del disco para medir aceleraciones

**Comment by rlrosa** [comment]
> 1. Hacer un código que vaya guardando en un archivo todos los datos que arroja la IMU.

el programa de [testeo de la imu](https://github.com/rlrosa/uquad/blob/master/src/test/imu_comm_test/imu_comm_test.c) hace esto.
te los da en 2 formatos:
- crudos, o sea, lo q leyó el ADC de 10 bits (0-1023)
- en unidades del mundo real, onda m/s^2, etc.

si lo corrés sin argumentos de puteo y dsp te explica como correrlo.
le pasás primero el device, y si le das otro argumento (cualquiera) asume que querés logear a archivos.
puede ser q se queje de q no existe el directorio _logs_, no verifiqué q se la bancara.
si no anda puede ser que tengas q hacer q exista este path:<pre><code>src/build/test/imu_comm_test/logs
</code></pre>

lo q vamos a usar es el segundo formato, pero hay q meterle huevo... para q esto sirva hay q calibrar de manera razonable, sino tira fruta.

creo que el issue #14 es previo a este.
con lo q hay se puede hacer lo de juntar datos, pero todavía no se puede masticarlos.
seguimo sobre esto en el #14

> 1. Planear rutas controladas y medibles para contrastar los resultados

cerré el issue #14, creo q se solapa con este.

el objetivo final de este issue es:
- estimar los params de un modelo <code>ax + b</code>.
  - el offset <code>b</code> se calcula haciendo la media de los datos con el imu quieto.
  - la ganancia <code>a</code> no se estima (por ahora). habría que hacer algo experimental para esto:

**Comment by spaternain** [comment]
Encontré un papper muy bueno sobre calibración de IMU. 
Les dejo el link: http://www.ee.kth.se/php/modules/publications/reports/2006/IR-EE-SB_2006_026.pdf

Tiene una cosa brava no más y es que se precisa hacer muchas rotaciones a distintas velocidades. Pero está super completo.

**Comment by spaternain** [comment]
Sin embargo para calibrar el acelerómetro alcanza con tomar medidas con la placa quieta orientada de 18 formas distintas. Eso se tiene que poder lograr medio facil

**Comment by mtailanian** [comment]
Rela, podés conseguir una foto de cómo se conecta el chip FTDI para comm imu - compu?

**Comment by rlrosa** [comment]
On Mon, Dec 26, 2011 at 2:30 PM, MatiTaila
reply@reply.github.com
wrote:

> Rela, podés conseguir una foto de cómo se conecta el chip FTDI para comm imu - compu?

no, no tengo.

creo que no hay muchas opciones, pero no estoy seguro.
hacé esto: fijate si hay tantos pines como slots en el conector.
si son la misma cantidad, entonces solo tenés dos opciones, una por
cada fila del conector. una de las filas tiene las cosas de interés, y
la otra no tiene nada, o sea que podés probar tranqui las dos y ver
cual anda, y no hace falta leer el resto de lo que mando.

si no son la misma cantidad, entonces tenés chance de cagar todo, xq
si alineás mal podés meter un vcc en el lugar equivocado, etc.

esta es la hoja de datos del ft2232h
http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT2232H.pdf
en la pág 8 te dice que señal va a cada lugar, dependiendo del modo.
lo que te importa son TXD y RXD, que van a ADBUS0 y ADBUS1

ahora hay que ver como están mapeadas esas dos líneas a los pines del
minimodule.
la info está en la pág 6 de
http://www.ftdichip.com/Documents/DataSheets/Modules/DS_FT4232H_Mini_Module.pdf
las líneas que queremos son AD0 y AD1
fijate ahí quien va a donde, y ahí vas a saber como va el conector.
tmb hay una tierra y un vcc en la vuelta, info sobre eso está en la
hoja de datoas del minimodule.

avisame si te trancás

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/16#issuecomment-3275714

## 

Rodrigo.

**Comment by mtailanian** [comment]
Demá, listo

**Comment by mtailanian** [comment]
Esto estaría medio listo pero ahora habría que calibrar la Mongoose...

**Comment by spaternain** [comment]
y este
