### ISSUE TITLE
Sniffer I2C

### ISSUE THREAD

**Issue by mtailanian** [rlrosa/uquad#17]
# The Fabulous Logic Analyzer

Seguir este [Link](http://tfla-01.berlios.de/)
1. Armar el hardware
2. Testear

**Comment by mtailanian** [comment]
El puerto paralelo entiende como nivel alto cualquier cosa mayor a 2.4V

Alimentando el buffer octal con 3.3V:
    1. Entiende a la entrada como nivel alto cualquier cosa mayor a 2.48V. Por lo tanto al entrarle con cosas entre 0 y 3.3 no habrìa problema
    2. Escupe a la salida 3.2V como nivel alto. Por lo tanto el puerto paralelo lo entiende sin nungún problema (3.2 > 2.4)

Parece que para el sniffer no necesitamos ningún conversor de niveles lógicos. Hoy llevo mi carcacha que tiene puerto paralelo y lo probamos. 

Lo otro bueno que probamos ayer es conectar las cosas al revés y a la saldia no escupía nada (0). Es decir que la computadora no va a tratar de escribir nada en el bus. Solo va a escuchar.

**Comment by spaternain** [comment]
Hay avances con esto???

Matute?? Has tenido tiempo de probar algo más??

**Comment by rlrosa** [comment]
la sigo acá, el sniffer ya fué, pero ta.

encontré un link en mikrocopter que tiene algo sobre un protocolo i2c xa manejar motores:

http://forum.mikrokopter.com/topic-923.html

hay código y todo
se puede ver si lo que tira el analyzador huele parecido a esto

**Comment by spaternain** [comment]
Bo, el mati ha encarado con esto. El otro día me estuvo mostrando lo que tiene y estamos (me incluyo) casi seguros de como funciona. Fue fundamental el sniffer. Para aseguranrnos de que las cosas son como pensamos vamos a precisar tener pronto el tema de poder hablar I2C. (El matute quedó en hacer esto una vez que volviera de sus vacaciones).

Vamo arriba gente, vamo que lo scamos entre los 4!

Esto fue una especie de aliento motivacional para arrancar con todo el año que viene y una especia de despedida al proyecto por unos días.

**Comment by rlrosa** [comment]
mati pinta meter un sniff al arranque a ver q onda?

**Comment by mtailanian** [comment]
Sabelooo, q rico cerrar esta issue
