### ISSUE TITLE
Shifter I2C

### ISSUE THREAD

**Issue by mtailanian** [rlrosa/uquad#18]
El bus i2C del quad funciona a 3.3V, mientras que el del analizador con 5V. Para poder utilizarlo necesitamos convertir esos niveles lógicos. [Acá](https://github.com/rlrosa/uquad/blob/master/doc_externa/I2C/I2C%20shifter.pdf) encontramos un shifter I2C que es una chotada y justamente por esto nos hace dudar.
Aparte se lo comentamos el Oliver y no se animó a jugársela, lo cual deja aún más dudas.

Léanse eso, estúdienlo y lo conversamos!

**Comment by rlrosa** [comment]
estuve viendo el adjunto.
el circuito no sirve.
para levantar el gate de los transistores hace falta VDD de por lo menos 3v, o sea que el 1.8 del beagle nos caga eso.

estoy viendo otras opciones, pero no se gasten con ese.

**Comment by mtailanian** [comment]
Igual acá la Beagle no tiene nada que ver. Si bien para la comm beagle-imu vamos a necesitar un shifter, acá estamos hablando de la comm entre el analizador TFLA y el bus i2c del quad.. es solo para sniffear...

Hay que volver a bicharlo, pero parece que alimentando el buffer con 3.3V puede andar todo sin necesidad de ningún shifter.

Dsp me fijo de nuevo y si anda ya cierro esta issue. Lo otro iría más bien [acá](https://github.com/rlrosa/uquad/issues/15)

**Comment by mtailanian** [comment]
Bueno parece que no es necesario este shfter, asi que cierro esta issue.
Nos ve!
