### ISSUE TITLE
alimentación beagle+imu+shifter+...

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#19]
tenemos que alimentar:
1. el/los level-shifters que usamos para la comm. Las tensiones necesarias son:
   - 1.8v
   - 3.3v
   - la tensión que necesite el i2c
2. la IMU
   - 5v

por ahora nada más (excepto el GPS pero asumo que come del USB)

en el expansion header de la beagle **1.8v** y **5.5v**  (pines 1 y 2 respectivamente)
- de la [datasheet del beagle](https://github.com/rlrosa/uquad/blob/master/datasheets/beagleboard/BBxMSRM_latest.pdf)

> 7.24.3 Power
> The expansion connector provides two power rails. The first is the VIO_1.8V rail which
> is supplied by the TPS65950. This rail is limited in the current it can supply from the
> TPS65950 and what remains from the current consumed by the BeagleBoard and is
> intended to be used to provide a rail for voltage level conversion only. It is not intended
> to power a lot of circuitry on the expansion board. All signals from the BeagleBoard are
> at 1.8V.
> The other rail is the DC_5V. The same restriction exits on this rail as mentioned in the
> USB section. The amount of available power to an expansion board depends on the
> available power from the DC supply or the USB supply from the PC.

Lo que yo entiendo es que hay que mirar  al TPS65950 para el rail de 1.8v, y a la beaglejuice para el de 5v.
- de la [hoja de datos del TPS65950](https://github.com/rlrosa/uquad/blob/master/datasheets/beagleboard/tps65950.pdf)
  - El rail de 1.8v tira **700mA** (de acá no queremos sacar casi nada, solo para alimentar el shifter, que debería comer a lo estrella pop no bulímica)
- de la [hoja datos de la imu](https://github.com/rlrosa/uquad/blob/master/datasheets/atomic_imu/datasheet_SFE-0012-DS-6DOFAtomic_v3.pdf)
  - A 5v consume **24mA**. Asumo que no vamos a tener problema para sacarle 24mA a la beaglejuice.

En fin, yo digo de alimentar tanto la IMU como el/los shifters desde la beagle
q opinan?

no apoyo el plan de armar un [circuito conversor de voltages como de la wiki](https://github.com/rlrosa/uquad/wiki/Conversor-de-Voltajes). creo que la vamos a complicar innecesariamente.

**Comment by spaternain** [comment]
Sabelo que todo come de la beagle!!

**Comment by mtailanian** [comment]
Ok! demá!

Para lo único que sirviría ese conversor de voltajes es para pasar de 5 a 3.3 en caso que algún shifter necesite 3.3
O que otra opcion hay?

**Comment by rlrosa** [comment]
la imu tiene 3.3v, podemos sacar de ahí (yo usé eso xa el shifter imu-beagle)

en la beagle tmb hay 3.3, pero no encontré una forma muy feliz de sacarlo para afuera (no está en un expansion ni en un test point)

**Comment by rlrosa** [comment]
creo que esto quedó resuelto

**Comment by mtailanian** [comment]
Da para pedirle a los padres de aquel que traigan unos max tamaño normal?

digo por las dudas q no podamos con estos...
si nos quedan unos max de más tampoco es tan grave... yo iria pidiendo... les parece?

**Comment by rlrosa** [comment]
2011/12/26 MatiTaila
reply@reply.github.com:

> Da para pedirle a los padres de aquel que traigan unos max tamaño normal?

encontraste max + grandes?
en digikey no vi

si no hay max grandes se puede buscar algo alternativo, que venga en
tamaño + práctico

> digo por las dudas q no podamos con estos...
> si nos quedan unos max de más tampoco es tan grave... yo iria pidiendo... les parece?

si vamo a pedir creo q hay q hacerlo ya, voy a averiguar cuando vuelven

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/19#issuecomment-3275975

## 

Rodrigo.

**Comment by rlrosa** [comment]
el 5 de enero se vienen los viejos d juan

**Comment by mtailanian** [comment]
Bueno esto quedó resuelto. Al final quedó así:
en 1 placa hay:
1. un conjunto de pines que van a Beagle hacia los pines Rx, Tx, SCL, SDA, GND y a las líneas de 5V y 1.8V
2. un conjunto de pines que van a la IMU: llega la línea de 5V y la imu devuelve a la placa una línea de 3.3V desde uno de sus pines. Además se conectan con la IMU los pines Tx, Rx y GND
3. un conjunto de pines que van hacia los ESCs conectando las líneas SCL, SDA y GND.

**En resumen la placa alimenta la IMU utilizando la energía de la Beagle y resuelve la conversión de niveles lógicos para la comunicación entre la Beagle y la IMU y entre la Beagle y los ESCs**

Esta issue quedó cerrada!
