### ISSUE TITLE
Calcular posición y orientación 

### ISSUE THREAD

**Issue by spaternain** [rlrosa/uquad#20]
Muchachada,

Creo que este es un tema que hay que discutir. Por lo que estuve mirando, no tengo ni idea como vamos a resolver esto. 

Por lo que estuve mirando, mucha gente usa acelerómetros para determinar la orientación. Sin embargo esto solo parece funcionar si el dispositivo está quieto (No acelerado). En estos casos los combinan con giróscopos y con un Kalman se logra una estimación muy buena.
Nuestro problema es que no está quieto el bicho. Así que en esto me parece que el acelerómetro no nos va a ayudar. Por otra parte, tenemos solo el giróscopo. Que aparentemente si lo usas solo no te da algo muy bonito. 

Queda planteada la pregunta como mierda determinamos la orientación.

Lo otro es el tema de la posición. El GPS por si solo, no es bueno. Hay que ver si podemos conseguir alguna corrección diferencial, ahí queda algo digno del orden de decenas de centímetro de error. Igual me parece demasiado. 
La otra opción es una vez conocida la orientación, si conozco las aceleraciones en teoría puedo integrar y sacar la posición.  Ahora, esto es una pija y tampoco funca. 

Queda planteado esto otro. 

No se. Escucho ideas/sugerencias

**Comment by rlrosa** [comment]
2011/11/15 spaternain
reply@reply.github.com:

> Muchachada,
> 
> Creo que este es un tema que hay que discutir. Por lo que estuve mirando, no tengo ni idea como vamos a resolver esto.
> 
> Por lo que estuve mirando, mucha gente usa acelerómetros para determinar la orientación. Sin embargo esto solo parece funcionar si el dispositivo está quieto (No acelerado). En estos casos los combinan con giróscopos y con un Kalman se logra una estimación muy buena.
> Nuestro problema es que no está quieto el bicho. Así que en esto me parece que el acelerómetro no nos va a ayudar. Por otra parte, tenemos solo el giróscopo. Que aparentemente si lo usas solo no te da algo muy bonito.

el gyro se porta bien, el problema es que tiene un drift.
si lo calibrás bien se la banca un ratito, pero dsp hay q darle un
toque con el acc xa volver.
frente a la falta de sensores se puede implementar un control q ayude,
por ejemplo, que el bicho se quede "quieto" de a ratos, y ahí recupere
la orientación con gyro+acc, y dsp arranque y se maneje solo con gyro
hasta la próxima parada.
el robotito de la empresa hace algo así (claro que "quieto" es mucho
más quieto en tierra que en el aire).

sobre orientación podemos agregar una brújula, como habíamos pensado
originalmente (con el razor 9DOF), o un sonar, o ver q onda hay por
ahí.
tamo a tiempo de agregar cosas, yo puedo llevar lo que haga falta.

> Queda planteada la pregunta como mierda determinamos la orientación.

el kalman del imu_display se la banca.
si agregamos info sobre "estoy quieto" o no, podemos implementar lo de
usar el acc solo cuando está parado (y ver q queda)

> Lo otro es el tema de la posición. El GPS por si solo, no es bueno. Hay que ver si podemos conseguir alguna corrección diferencial, ahí queda algo digno del orden de decenas de centímetro de error. Igual me parece demasiado.

cámara?

> La otra opción es una vez conocida la orientación, si conozco las aceleraciones en teoría puedo integrar y sacar la posición.  Ahora, esto es una pija y tampoco funca.

yo hice un par de pruebas chiquitas, y me dió bastante fruta, onda
centímetros resultaron en decenas de centímetros.
igual no hice nada por compensar la ganacia del acc, ni problemas del
ADC, etc, o sea que se podrías conseguir algo mejor.
yo tmb leí q lo de acc para pos no sirve...

> Queda planteado esto otro.
> 
> No se. Escucho ideas/sugerencias

hay q pensarla bien, pero quedan montones de opciones:
- sonar
- IR
- presión
- brújula
- un kinect jej

## 

Rodrigo.

**Comment by spaternain** [comment]
La idea de hacer un control que lo deje quieto no me convence en el hecho de que no puedo saber con exactitud si estoy quieto. El accelerómetro es bastante dudoso. Capaz que si se puede, pero no estoy del todo seguro que tan bien va a andar esto. Si anda no me parece una mala solución. 

Al principio de todo, cuando definimos las compras me parece que si hubiera sido necesario algún otro sensor canetti nos podría haber dicho. Incluso le planteamos comprar un IMU con magneto, pero le pareció al pedo. Capaz que no encaró, puede ser. Estaría bueno agitarlo capaz y aprovechar antes de que rodrigo vuelva. 

El tema de la cámara es que precisas demasiada información sobre el lugar donde estás volando, entonces no te queda demasiado versátil. No es una idea que me motive demasiado. 

El sonar y el IR son buena cosa si queres hacer evasión de objetos, o si conoces un poco la geometría del lugar (idem que la cámara me parece)

La brújula está bien porque me garantiza la orientación, al menos en 2D. No se si puedo distinguir bien todos los ángulos. No se que pasa si apunto con una brujula para arriba.....

Presión: Puede dar una buena idea para la altura, sin embargo sigue sin resolver las otras direcciones.

**Comment by rlrosa** [comment]
2011/11/17 spaternain
reply@reply.github.com:

> La idea de hacer un control que lo deje quieto no me convence en el hecho de que no puedo saber con exactitud si estoy quieto. El accelerómetro es bastante dudoso. Capaz que si se puede, pero no estoy del todo seguro que tan bien va a andar esto. Si anda no me parece una mala solución.
> 
> Al principio de todo, cuando definimos las compras me parece que si hubiera sido necesario algún otro sensor canetti nos podría haber dicho. Incluso le planteamos comprar un IMU con magneto, pero le pareció al pedo. Capaz que no encaró, puede ser. Estaría bueno agitarlo capaz y aprovechar antes de que rodrigo vuelva.
> 
> El tema de la cámara es que precisas demasiada información sobre el lugar donde estás volando, entonces no te queda demasiado versátil. No es una idea que me motive demasiado.

la cam (al piso) se podría usar xa saber q estás medio quieto, viendo
las diff entre imágenes sucesivas.
si tas medio quieto podés usar los acc xa recalibrar un poco...
(creo)

> El sonar y el IR son buena cosa si queres hacer evasión de objetos, o si conoces un poco la geometría del lugar (idem que la cámara me parece)
> 
> La brújula está bien porque me garantiza la orientación, al menos en 2D. No se si puedo distinguir bien todos los ángulos. No se que pasa si apunto con una brujula para arriba.....
> 
> Presión: Puede dar una buena idea para la altura, sin embargo sigue sin resolver las otras direcciones.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/20#issuecomment-2783597

## 

Rodrigo.

**Comment by spaternain** [comment]
De acuerdo, para eso si se puede usar

**Comment by rlrosa** [comment]
Estuve viendo un poquito.
Hay breakout boards xa magnetómetros por USD15
La razor que habíamos visto me parece q no da, vale como 125 y en la web le tiran un montón de palo.
la [mongoose](http://store.ckdevices.com/products/Mongoose-9DoF-IMU-with-Barometric-Pressure-Sensor-.html) me parece que encara más. tiene
- 3 axis acc
- 3 axis gyro
- 3 axis magnet
- barometer

y vale USD 111.
hice una pregunta (si podíamos darle con 5v) y me contestaron en 5 minutos jej.

si compramos algo medio caribe la imu igual queda xa cualquiera que quiera hacer cosas en la fac
un autito, por ejemplo, estaría re gozado con la imu. se queda quieto xa calibrar y listo. a lo que voy es a que no es que tiramos plata del proyecto a la basura.

**Comment by spaternain** [comment]
Bueno,

Me parece que la forma que el loco del papper resuelve el tema de la orientación y posición del bicho está muy buena. No es demasiado complicado al parecer, da buenos resultados y no nos implicaría traer nada más, además de ser una solución bastante elegante :-P.

Yo me comprometo a meterle a esto: Para empezar, hacer un programita en MatLab que pueda a partir de los datos leidos calcular la posición y orientación. Después se puede probar a ver que tan posta anda y por último pasarlo a C.

No creo que arranque antes del martes por culpa de los parciales. Así que hay un poco de tiempo para decidir.

Salute

**Comment by rlrosa** [comment]
en el paper del EKF hay una tablita, en la pag 16, que según lo que entiendo es lo que le piden del sistema, en términos de precisión.
la posición tiene un sigma de 10m, que creo que significa que tu posición va a estar en x+-10m... eso no nos sirve... no?
el sistema este está pensado para algo que va derecho un montón, tipo nave espacial/avión. ahí supongo q no tenés tanto lio, xq tu posición no es tan loca, onda si vas xa adelante al mango no vas a doblar tanto, en compración con lo que vas a avanzar.
me parece que hay que buscar papers de quads, no te aviones.
tmb se podría implmentar un comportamiento que haga q el sistema este sea compatible...

en fin, creo que hay q mirar un poco más, ya estamos cerca del límite para encargar cosas.
insisto en que comprar cosas demás no es despilfarro, una IMU le sirve a cualquiera en la facu que quiera trabajar con algo de robótica, por ejemplo a los robocrotos del inco, etc.

**Comment by spaternain** [comment]
Igual capaz que funciona igual para nuestro sistema. Digo, el loco no dice (o capaz que me lo comí) que con otros requerimientos no ande. El tipo dice hace un estimador que le erre por menos de 3 sigma. Si nuestros sigmas son menos puede estar bien. Hay que ver los sigmas de nuestros sensores.

**Comment by spaternain** [comment]
No creo que tengamos nada mucho mejor que eso con nuestro GPS si lo usamos así no más. Sin embargo con la estación de referencia de la fing podemos mejorarlo. Investigo un poco más a ver que otras opciones aparecen.

**Comment by rlrosa** [comment]
alguna novedad con esto?

alguno puede bajar esto en la fac: http://ieeexplore.ieee.org/xpl/freeabs_all.jsp?arnumber=5509980

capaz está bueno hablar con el canetti a ver q dice respecto a sensores y cosas.
el equipo que tenemos es lo que pidió, él, pero él tenía la cabeza en un avión. el heli es como que más xa la chiquita, y capaz hace falta algo que nos permita tener más precisión que el planeó.
yo le preguntaríá un par de cosas:
- sensores? así en genérico, a ver q dice.
- cámara al piso?

yo estuve viendo y hay un montón que se manejan con acc y gyro y poco más, sensor de presión blabla
el tema es que son todos juguetes RC, entonces de última tenés el feedback del usuario que te la toca todo el tiempo...

por un rato (1 semana **A REVENTAR**) tenemos placas/sensores por chirolas.
dsp ya es shipping gigante, aduana, etc...
yo sigo mirando.

**Comment by spaternain** [comment]
Yo estuve mirando un poco más, pero sin llegar a nada concluyente. Hoy bajo ese papper en la fing. 
A mi me dio la misma sensación que a vos, o sea.... con el giro y acc + algo más haces que te ande lindo a control remoto.... con el giro y acc + GPS haces que un avión ande bien (tenes más tolerancia en cuanto a la exactitud de la posición). 

Voy a seguir investigando igual. 

Reunion con Canetti: Para juntarnos con canetti habría que tener pronta la distribución de tareas que nos pidió y algo de los ESC. Yo se que están re complicados, pero podríamos tratar de juntarnos un día (jueves??) a liquidar esas cosas. Por lo menos probar el TFLA en la compu del matute. Sino Canetti me parece que nos va a mandar a cagar..

**Comment by spaternain** [comment]
Ya lo subí

**Comment by spaternain** [comment]
Agregue otro paiper.... los locos obtienen un resultado muy bueno. Tendríamos que agregar un barómetro a lo que tenemos... Este si no anda el GPS me parece que muere.... por ahí vi otros que mismo si se les muere el GPS, pero tienen magneto se mueven bien.

No tengo ni idea como todavía.... pero, me da la impresión que con acc, gyro, GPS, barometro y magnetometro te manejas rico rico

**Comment by spaternain** [comment]
Esto es lo que hay que explicarle a Canetti cuando hablemos el jueves/viernes.

1- Sensores inerciales: Los únicos que estaban al alcance de la mano (económicamente hablando) tienen errores de ruido y un bias aleatorio. Esto se puede paliar un poco con filtros de Kalman, pero es imposible tener más de algunos segundos sin que la posición diverja demasiado (Esto es ayudando acc y gyro con magneto y baro). Supongo que esto lo sabía, y por eso nos recomendó comprar un GPS....

2- El GPS no tiene una gran precisión... el nuestro nos afirma que el error es menor a 5m con un 50% de probabilidad... esto es bastante malo si queremos hacer algo con precisión (me parece que es la idea). Me sorprende que Canetti no supiera esto o no lo haya tenido en cuenta. Existen formas de reducir este error con correcciones diferenciales, hoy voy a hablar con la gente de Geodesia a ver si hay alguna solución viable con esto. Les cuento que me dicen así vamos con las cosas claras al jueves.

3- Opciones:  - Un GPS de 20000 dólares y que el quad no puede levantar, pero que te da precisión submétrica 
                    - Un GPS con corrección diferencial (no se si podremos usar el nuestro) y tener algun metrito de error
                    -Cámara, buena presición, pero quedamos acotados a tener mucha información sobre el entorno
                    -Cambiar el enfoque de la aplicación y hacer algo más grosero

Ese es el análisis que hago de la situación a partir de las cosas que fui leyendo por ahí. Ninguna solución por ahora es muy alentadora en mi opinión.

Comenten

**Comment by spaternain** [comment]
Nadie me da bola chupense una pija

**Comment by rlrosa** [comment]
yo voto x la cam, como siempre jej
xq decis mucha info?
capaz alcanza con las diff, eso te daria + info xa meter en el kalman
sobre xa donde te moviste y cuanto. si la vibracion del quad no te
mata capaz encara
no me cuelga el gps de USD 20k

lo del grosero no me gusta...
creo q la joda de un quad es que puede ir despacito y para y blabla

2011/12/7 spaternain
reply@reply.github.com:

> Nadie me da bola chupense una pija
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/20#issuecomment-3050029

## 

Rodrigo.

**Comment by spaternain** [comment]
La cámara lo que tiene es que si el terreno en el que te moves es muy uniforme (el campo uruguayo x ejemplo) no se que tanto te podes dar cuenta si te moviste o cuanto te moviste con dos fotos sacadas en momentos distintos.

Por lo general, cuando hacen cosas con cámaras precisan información sobre el cuarto, o sea, si yo quiero que haga cierta ruta le tengo que poder decir de alguna forma por donde quiero que vaya. Si no se nada de donde estoy es muy dificl decirle algo, esa es la principal ventaja del GPS.

El GPS de 20k obviamente no pinta pa nada, lo grosero tampoco.

Ayer llamé al de geodesia varias veces pero no me atendió. Tampoco me ha contestado los mails. Hoy pruebo otra vez.

**Comment by rlrosa** [comment]
2011/12/7 spaternain
reply@reply.github.com:

> La cámara lo que tiene es que si el terreno en el que te moves es muy uniforme (el campo uruguayo x ejemplo) no se que tanto te podes dar cuenta si te moviste o cuanto te moviste con dos fotos sacadas en momentos distintos.
> 
> Por lo general, cuando hacen cosas con cámaras precisan información sobre el cuarto, o sea, si yo quiero que haga cierta ruta le tengo que poder decir de alguna forma por donde quiero que vaya. Si no se nada de donde estoy es muy dificl decirle algo, esa es la principal ventaja del GPS.

los maus que opticos, los de la lucecita roja, usan una camara (la luz
es xa iluminar no+) y con eso hacen tracking.
andan en casi cualquier superficie, con q tenga un poco de textura. el
campo tiene textura, capaz se puede

> El GPS de 20k obviamente no pinta pa nada, lo grosero tampoco.
> 
> Ayer llamé al de geodesia varias veces pero no me atendió. Tampoco me ha contestado los mails. Hoy pruebo otra vez.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/20#issuecomment-3050444

## 

Rodrigo.

**Comment by spaternain** [comment]
Muy interesante, no sabía que funcionaran así. Pensé que rebotaba la luz no más y hacían algo con eso. 

Igual me parece que el problema de la cámara es que siempre precisas una referencia externa. Mareo al quadcopter, lo pongo en un lugar que no conoce. Si le pido que llegue a algún lugar no sabe. 

Igual ta, si te robo el quad y lo meto bajo techo con el GPS tampoco se escapa. Igual me da la sensación de que si puede lograr una buena precisión es más robusto.

**Comment by rlrosa** [comment]
2011/12/7 spaternain
reply@reply.github.com:

> Muy interesante, no sabía que funcionaran así. Pensé que rebotaba la luz no más y hacían algo con eso.
> 
> Igual me parece que el problema de la cámara es que siempre precisas una referencia externa. Mareo al quadcopter, lo pongo en un lugar que no conoce. Si le pido que llegue a algún lugar no sabe.

toy d acuerdo.
yo pensaba usar la cam xa ayudar a los acc.
el problema es q no sabes donde estas, pero suponete que de alguna
manera te das cuenta, x ej arrancas de un lugar conocido. si tenes
medidas diff razonables (lo que pensabamos hacer integrando acc)
entonces capaz el drift no se te va tanto.

> Igual ta, si te robo el quad y lo meto bajo techo con el GPS tampoco se escapa. Igual me da la sensación de que si puede lograr una buena precisión es más robusto.

ai agree.
podemos ponerle moco asi nadie se lo roba.

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/20#issuecomment-3050665

## 

Rodrigo.

**Comment by spaternain** [comment]
La idea es GPS/cámara para ver donde estoy cada cierto tiempo, IMU para la cortita (tipo filling the blanks...)

Si con la cámara arrancas siempre de un lugar conocido y se puede hacer algo tipo mouse optico me parece que está bueno. Lo que tiene es que me imagino que a medida que te moves el error es cada vez más grande. 

El GPS te acota ese error

**Comment by spaternain** [comment]
Vengo con noticias bastante buenas:

Me junté un rato hoy con Roberto Rondín, es un docente de geodesia del instituto de Agrimensura. Los locos trabajan abundante con temas de GPS y eso así que me pareció una buena iniciativa juntarme a charlar con el, o con alguien del grupo. El loco la verdad que es macanudo, quedó en mandarme algunas informaciones, así que cuando lo tenga lo mando o lo subo al git.

La mejor noticia es esta: El GPS tiene un error absoluto que puede ser de 10 metros, pero medida a medida no hay prácticamente error. O sea, si "corremos el cero" capaz que nos podemos manejar bien de bien. Igual, me ofreció (para que vean lo macanudo que es el tipo) salir a dar unas vueltas con nuestro gps y con un gps con correcciones que tienen ellos para ver que tanta diferencia hay. El dice que ha hecho cosas similares y que la diferencia no es mucha. 

Le conté que con el Mati, habíamos puesto las coordenadas que daba el gps en el google earth y que nos había dado cualquiera. Me dijo que era normal, que los mapas del google earth no están bien calibrados y que es muy probable que los errores sean importantes. De hecho, me dijo que si ves google earth un día y lo volves a ver un tiempito después (si cambiaron las fotos) están corridas. Así que ta, me recomendó repetir la prueba con un mapa más calibrado. Dice que el de la intendencia está bien. 

Me dijo que en el peor de los casos, si eso no nos alcanza podemos hacer una corrección diferencial, para eso hay que comprar un GPS que acepte RTCM o NTRIP y abrir una conexión con una dirección IP y un puerto y ahí ya tenes todo resuelto. 

Plan: Hacer un programita que guarde las coordenadas del GPS con la hora. Rodrigo si podés please metele a esto. Seguro que lo sacas en dos patadas. 
Repetir el experimento que hicimos con el Mati. 
Hacer un test drive una vez que esté pronto el programa. 
Rezar porque nuestro bicho sea suficiente.

Opinene

**Comment by rlrosa** [comment]
d fiesta!

2011/12/7 spaternain
reply@reply.github.com:

> Vengo con noticias bastante buenas:
> 
> Me junté un rato hoy con Roberto Rondín, es un docente de geodesia del instituto de Agrimensura. Los locos trabajan abundante con temas de GPS y eso así que me pareció una buena iniciativa juntarme a charlar con el, o con alguien del grupo. El loco la verdad que es macanudo, quedó en mandarme algunas informaciones, así que cuando lo tenga lo mando o lo subo al git.
> 
> La mejor noticia es esta: El GPS tiene un error absoluto que puede ser de 10 metros, pero medida a medida no hay prácticamente error. O sea, si "corremos el cero" capaz que nos podemos manejar bien de bien. Igual, me ofreció (para que vean lo macanudo que es el tipo) salir a dar unas vueltas con nuestro gps y con un gps con correcciones que tienen ellos para ver que tanta diferencia hay. El dice que ha hecho cosas similares y que la diferencia no es mucha.
> 
> Le conté que con el Mati, habíamos puesto las coordenadas que daba el gps en el google earth y que nos había dado cualquiera. Me dijo que era normal, que los mapas del google earth no están bien calibrados y que es muy probable que los errores sean importantes. De hecho, me dijo que si ves google earth un día y lo volves a ver un tiempito después (si cambiaron las fotos) están corridas. Así que ta, me recomendó repetir la prueba con un mapa más calibrado. Dice que el de la intendencia está bien.
> 
> Me dijo que en el peor de los casos, si eso no nos alcanza podemos hacer una corrección diferencial, para eso hay que comprar un GPS que acepte RTCM o NTRIP y abrir una conexión con una dirección IP y un puerto y ahí ya tenes todo resuelto.
> 
> Plan: Hacer un programita que guarde las coordenadas del GPS con la hora. Rodrigo si podés please metele a esto. Seguro que lo sacas en dos patadas.

en una semana arranco jej

> Repetir el experimento que hicimos con el Mati.
> Hacer un test drive una vez que esté pronto el programa.
> Rezar porque nuestro bicho sea suficiente.
> 
> Opinene
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/20#issuecomment-3054258

## 

Rodrigo.

**Comment by spaternain** [comment]
Cierro este issue
