### ISSUE TITLE
beagleboard - KO

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#21]
Necesito info sobre la compra para llenar el RMA.
mandé mail y no dieron bola, creo que se perdió en la cadena, o nunca lo mandé, no se.
agrego acá q es más ordenado. (acuérdense de ir cerrando las cosas q se terminan)

necesito completar:
- Company
- Address
- Phone
- Email

pensaba poner _mis_ datos, para que el proceso sea más fácil y rápido.
q dicen?

**Comment by mtailanian** [comment]
Creo que [acá](https://github.com/rlrosa/uquad/blob/master/compras/Ordenes%20de%20compra/Facturas/WowHobbies.pdf) está todo...

Fijate y sino cualquier cosa avisá...

**Comment by rlrosa** [comment]
mandé mail al veterinario, el RMA
busqué un tel de contacto xa poder agitar, pero no encontré nada. te tiran a los foros, y ahí ya estuve (y me mandaron al RMA).
llené el RMA y mandé, pero eso fue el miércoles. ayer fue feriado acá
(pavo day) y hoy creo que medio q tmb, o sea que recién el lunes van a
mirar.
lunes de tarde llamo a ver de que la juegan.
quiero convencerlos de que me manden una sin q les hayamos mandado la
rota, así que me puedo llevar la sana conmigo (ni a palo da en 2
semanas xa que manden desde ahí, llegue, revisen, me manden otra y
todo antes del 13).

(esto es copia de un mail, puse acá xa que quede ordenado)

**Comment by rlrosa** [comment]
in da jaus beibi!

**Comment by mtailanian** [comment]
Llegó?
Avisas cuando llegue?

**Comment by rlrosa** [comment]
2011/12/5 MatiTaila
reply@reply.github.com:

> Llegó?
> Avisas cuando llegue?
> 
> ya la tengo!  :)

"in da haus"!

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/21#issuecomment-3026521

## 

Rodrigo.

**Comment by mtailanian** [comment]
Sabelo!!! anda bien? je..

**Comment by rlrosa** [comment]
Una buena y una mala... 1 + 1 == 0 en algunas cosas :(

la nueva anda bien.
la mia no lee la SD. (la misma tarjeta que funca en la nueva **no** funca en la mia, probé varias veces).

agité a los beagles a ver q onda, capaz pinta otra RMA...
el problema que vimos no es exactamente el mismo, la mia levanta el boot y se caga dsp, pero capazq tamos haciendo algo raro.
no me gusta nada.

el proceso es:
1. mandar al foro
2. si el foro te dice q pidas RMA, pedís RMA.
3. te mandan una nueva.

toy en la etapa 1, y no tengo mucho tiempo...
igual lo padres de juan vienen en dic, capaz le podemos clavar una beagle.

vamo a ver q dicen.

salú.

**Comment by rlrosa** [comment]
parece que me cambian la mia tmb.
me van a mandar una nueva, con un label xa devolver la rota sin tener que pagar ni shipping.
fue bcc del mail a uquad

**Comment by spaternain** [comment]
Esto también no??

**Comment by rlrosa** [comment]
falta llegar 1

On Wed, Dec 7, 2011 at 9:14 AM, spaternain
reply@reply.github.com
wrote:

> Esto también no??
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/21#issuecomment-3050009

## 

Rodrigo.

**Comment by spaternain** [comment]
Si... ya sé... pero ta... me parece que daba pa dejar cerrado

**Comment by rlrosa** [comment]
tengo las dos sanas, la mandaron overnight, vino d toque.

toy viendo si puedo hacer andar mi SD con la beagle nueva, xa descartar rarezas.
hice un backup de una de las SD 0km, por si acaso.

2011/12/7 spaternain
reply@reply.github.com:

> Si... ya sé... pero ta... me parece que daba pa dejar cerrado
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/21#issuecomment-3050469

## 

Rodrigo.

**Comment by spaternain** [comment]
No rompas nada x favor....

**Comment by rlrosa** [comment]
decís que mejor esperar al diagnóstico?

los tipos dicen que SIEMPRE pudieron reparar las placas que llegaron
al hospital.

On Fri, Dec 9, 2011 at 2:20 AM, spaternain
reply@reply.github.com
wrote:

> No rompas nada x favor....
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/21#issuecomment-3077345

## 

Rodrigo.

**Comment by spaternain** [comment]
Yo esperaría al diagnóstico.... sería una pija volver a cagarla con lo mismo, pero bueno..... ya estas grande

**Comment by rlrosa** [comment]
ok. la q rompí yo lee medio q aleatorio de la SD. cloné el contenido
de la SD nueva a la vieja, y a veces arranca, a veces no, avanza más o
menos.
en fin, yo apostaría a que es el conector xa la SD.
venden de esos ahí?

yo voy a ver si roberto tiene alguno q me regale

On Fri, Dec 9, 2011 at 8:30 AM, spaternain
reply@reply.github.com
wrote:

> Yo esperaría al diagnóstico.... sería una pija volver a cagarla con lo mismo, pero bueno..... ya estas grande
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/21#issuecomment-3081955

## 

Rodrigo.

**Comment by spaternain** [comment]
Ya estas para ir a trabajar al hospital de perros....

Ni puta idea si venden de esas cosas....Si se puede conseguir de arriba mejor
