### ISSUE TITLE
arreglar wiki SD card

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#22]
Lo que había armado para preparar la SD para el beagle no parece funcionar con la XM. lo hice probando con la vieja.

hoy probando el tercer shifter que armé (este quedó prolijo) cagué la SD (no se como, pero se que no pude probar el circuito...) y no la pude recuperar con la wiki, o sea que no anda.
tengo q arreglar eso

conclusión: **no usen** la wiki [BeagleSDBoot](https://github.com/rlrosa/uquad/wiki/BeagleSDBoot) :(

**Comment by mtailanian** [comment]
Capaz q era tu tarjeta q estaba cagada...

yo la usé varias veces a esa wiki... y andó

**Comment by rlrosa** [comment]
puede ser...
en unos dias me llegan las nuevas y veo...

igual habria que estar atentos a como manipulamos las SD
capaz hay algun bug de hardware que rompe tarjetas/beagles

**Comment by spaternain** [comment]
Esto da para cerrarlo no?? 
Si alguien quiere dejarlo abierto siéntanse libres

**Comment by rlrosa** [comment]
si uds probaron y anduvo cerralo no+, yo no me acuerdo si lo llegue a
usar con una XM.

On Wed, Dec 7, 2011 at 9:13 AM, spaternain
reply@reply.github.com
wrote:

> Esto da para cerrarlo no??
> Si alguien quiere dejarlo abierto siéntanse libres
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/22#issuecomment-3050000

## 

Rodrigo.

**Comment by spaternain** [comment]
Nosotros porbamos la beagleSDboot, pero después de que no andaba la beagle. 
Así que no se.

**Comment by rlrosa** [comment]
yo pruebo cuando me llegue la 2da y dsp cierro (o no)

On Wed, Dec 7, 2011 at 9:41 AM, spaternain
reply@reply.github.com
wrote:

> Nosotros porbamos la beagleSDboot, pero después de que no andaba la beagle.
> Así que no se.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/22#issuecomment-3050502

## 

Rodrigo.

**Comment by spaternain** [comment]
dale, tratá de no romper

**Comment by mtailanian** [comment]
Ta, probado y no rompe nada...

cierro!
