### ISSUE TITLE
compras dic '11

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#23]
# tarjetas microSD

llevo algunas?
la mia creo que se hizo mierda, o algo del estilo.
mi beagle arranca, pero no le gusta lo que encuentra en la SD.
tengo q comprar otra xa probar, valen tipo 6-7 USD.
el lunes se supone que hay ofertas locas online, es el dia de "gastemos plata" acá, así que es un buen momento xa comprar cosas a buen precio.
yo llevaría 4 o 5
q dicen?
# quita estaño

agrega dos quita estaños a la lista de compras, salen USD 5 cada rollito. es esa cinta mágica que le das con el soldador y se sale.
hay d eso por ahí? (en la fac y/o en rondeau?)

quiero confirmación de parte de uds para todas las compras.
no entendí a que se refieren con "pines". podrían mandar foto?

**Comment by spaternain** [comment]
Me parece bien ambas compras

**Comment by rlrosa** [comment]
sigo sin saber a que se refieren con "pines"

muchachos cualquier cosa que se les ocurra, si voy a comprar algo tiene que ser dentro de muy poco.

**Comment by mtailanian** [comment]
Pines ya conseguimos, don't guorri

**Comment by rlrosa** [comment]
sabemos algo sobre esto:
- LED IR
- Fototransistor IR

cualquiera sirve?
componentes de los grandotes, no? con patitas, etc (**NO** smd)

**Comment by mtailanian** [comment]
No sabemos nada de eso (por lo menos yo)

Parece como que cualquiera sirve...

de los grandotes si

**Comment by rlrosa** [comment]
ok, tonce creo que consigo gratis.
el bicho q venden acá tiene IR y photodiodos, así que deben tener xa
tirar xa arriba.

hao!

On Wed, Nov 30, 2011 at 2:32 AM, MatiTaila
reply@reply.github.com
wrote:

> No sabemos nada de eso (por lo menos yo)
> 
> Parece como que cualquiera sirve...
> 
> de los grandotes si
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/23#issuecomment-2957697

## 

Rodrigo.

**Comment by mtailanian** [comment]
Demá!

**Comment by rlrosa** [comment]
mati me pasó este link: http://airsoftguns.ie/670-thickbox/pas-74v-2200mah-15c-li-po-battery-handguard-type-t-plug.jpg
eso es el conector que hace falta.
el rojo, no?

sobre los MAX, conseguí MAX3373EEKA
todavía no se cuantos.
cuantos hacen falta?
si la cantidad alcanza no hace falta más MAXXXXX, no?
en la lista de compras hay un montón, pero según entiendo con estos alcanzaría

la parte del IR conseguí en la empresa.

**HOY** quiero meter la orden, sino capaz no llega  a tiempo.
igual aparentemente no es mucha cosa, aguante evo :P

**Comment by mtailanian** [comment]
Si si el Rojo!!

eso de q puse muchos maxes era por poner diferentes alternativas. Si conseguiste uno de los q son para imu-beagle y otro de los q sirven para comm i2c ya alcanza!

**Comment by rlrosa** [comment]
los que consegui son bidir de 2 canales.
eso para la beagle-imu sirve.

para el i2c tmb?

**Comment by mtailanian** [comment]
Si, también.

Habíamos diferenciado porque hablamos que para la comm beagle-imu preferíamos canales unidireccionales.
Solo por prolijidad digamos... por las dudas... 

supogo q si traes solo bidireccionales está bien...
si es fácil y no te embola podés pedir de los otros tambien.... como quieras...

**Comment by rlrosa** [comment]
2011/12/2 MatiTaila
reply@reply.github.com:

> Si, también.
> 
> Habíamos diferenciado porque hablamos que para la comm beagle-imu preferíamos canales unidireccionales.
> Solo por prolijidad digamos... por las dudas...
> 
> supogo q si traes solo bidireccionales está bien...
> si es fácil y no te embola podés pedir de los otros tambien.... como quieras...

si hago pedido meto.
igual tengo los q usan los inversores, esos son unidir

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/23#issuecomment-2993544

## 

Rodrigo.

**Comment by rlrosa** [comment]
parece que el "soder wick" consigo en evo tmb.

no hay 74HC245. hay 244, pero es distinto (**no** es bidir) y no sirve.
compro?

parece que el conector de la bat se llama Molex, pero no puedo saber tamano...
necesito + info, medidas o algo para poder encargar.

quiero pedir hoy...

**Comment by rlrosa** [comment]
tengo los max, son 9.
son chiquitos, SMD, vamo a tener q tener cuidado para soldarlos sin cagarla, y capaz tener algunas plaquita como la gente.

se consiguen plaquitas para montar bichos?
pater vs sabes hacerlas de electronica2?

**Comment by spaternain** [comment]
Si... andamos rico pa eso.... vos tranqui...

Bo, dado que no sabemos mucho como hacer bien lo de los sensores: pa mi se compra la razor 9DOF que tiene magneto y un barómetro. El jueves nos vamos a juntar con canetti, pero va a ser tarde para definir.

Acá con los pibes decimos de comprar 6 pwm, por si los esc estos con I2C no nos conducen a ninguna parte

Otra, conseguite un sniffer de I2C. Ojo que tiene que poder andar en I2C rápido 400KHz

**Comment by spaternain** [comment]
> "no hay 74HC245. hay 244, pero es distinto (no es bidir) y no sirve.
> compro?"

Son los buffer eso?? no precisamos que sean bidireccionales. Trae el que haya. 

> parece que el conector de la bat se llama Molex, pero no puedo saber tamano...
> necesito + info, medidas o algo para poder encargar.
> Te mandamos la foto

**Comment by rlrosa** [comment]
2011/12/2 spaternain
reply@reply.github.com:

> > "no hay 74HC245. hay 244, pero es distinto (no es bidir) y no sirve.
> > compro?"
> 
> Son los buffer eso?? no precisamos que sean bidireccionales. Trae el que haya.

el mati pidio estos. son algo del circuito del i2c.
no creo que sea irrelevante lo del bidir
mati?

> > parece que el conector de la bat se llama Molex, pero no puedo saber tamano...
> > necesito + info, medidas o algo para poder encargar.
> > Te mandamos la foto

parece que el connector ese no es molex
se llama "deans"
q queremos?
macho? hembra?
algo como esto les gusta:
http://www.ebay.com/itm/10-pair-T-Plug-Connectors-Deans-Style-Male-and-Female-Connectors-/260881208496?pt=Radio_Control_Parts_Accessories&hash=item3cbdbb54b0#ht_500wt_922

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/23#issuecomment-2996570

## 

Rodrigo.

**Comment by rlrosa** [comment]
compré los connectores esos.
roberto va a ver si consigue muestras de los 74HC245. serían lo único que nos falta pedir.

como hacen para armar circuitos?
hay protocosas en el iie?
no hace falta nada d eso?
no hay nada por lo que siempre puteen? (aparte del proyecto en gral)

**Comment by spaternain** [comment]
No, de esas cosa siempre hay.
Bo, viste lo de los sensores??? vamo a comprar algo más de eso???
algo para decodificar el I2C???

**Comment by rlrosa** [comment]
tres cosas:
1. placa con sensores voto por esta: http://store.ckdevices.com/products/Mongoose-9DoF-IMU-with-Barometric-Pressure-Sensor-.html
   habria que comprar 2....
2. encontre un i2c razonable y q llega a tiempo http://www.ebay.com/itm/PC-USB-Logic-Analyzer-100MHz-64Mb-memory-/250684716233?pt=BI_Analyzers&hash=item3a5df934c9#ht_1291wt_1348
3. no entiendo a q se refieren con "6 PWM". tenemos "brushless" motors, no vale mandarles un PWM así nomás...
   me estoy perdiendo de algo?
   no habría q comprar esc?

bola pls...

**Comment by spaternain** [comment]
1.Ta buena la placa... por lo que estuve leyendo con acc, gyro, mageneto y barómetro nos manejamos bien. No me gusta mucho que sea I2C, pero bueno. No es tan grave

2.Me gusta, si Samplea a 100MHz estamos gozados
1. PWM no, ESC precisamos. Podríamos comprar motores también, por si el ESC no llegase a ser compatible con los motores que ya tenemos

**Comment by rlrosa** [comment]
juan (braga) me dijo que ellos compraban cosas xa el proyecto a travéz
de miami box.
sino tmb se puede comprar y mandar a los pibes en evo, y que ellos nos
manden a nosotros.
el punto es que esta no es nuestra última chance para comprar cosas.
las cosas grandes si mejor las llevo yo, pero los componentes que
necesitemos dsp se pueden pedir.

2011/12/3 spaternain
reply@reply.github.com:

> 1.Ta buena la placa... por lo que estuve leyendo con acc, gyro, mageneto y barómetro nos manejamos bien. No me gusta mucho que sea I2C, pero bueno. No es tan grave

no es i2c, la data va x serial, como la imu.
el i2c es para debugging.

> 2.Me gusta, si Samplea a 100MHz estamos gozados

chicas si están de acuerdo compro. por ahora solo pater aprobó
hay que hacerlo YA, sino vamo a tener que pagar shipping rápido al pedo.

> 1. PWM no, ESC precisamos. Podríamos comprar motores también, por si el ESC no llegase a ser compatible con los motores que ya tenemos

uds vieron algo sobre esto?
yo estaría arrancando de 0 a elegir, no se ni bosta.
estuve viendo un poco y me da la impresión de que los esc se manejan con pwm. la continua (el ciclo de trabajo) indica la velocidad a la que querés correr el motor, y el circuito en el esc se encarga de darle con esa pulenta a las cosas en el orden necesario xa que funcione todo ok.
eso me haría pensar q es todo medio compatible.

los de wowhobbies, que parecen ser los mismos que estos http://turboace.com/Page_2.html  parecen ser de 10A, o sea que ese sería el único requisito

agité a la gente de wowhobbies, a ver que me saben decir sobre los motores, sino estaríamos comprando ESCs a ciegas, y capaz ni vale la pena.
tienen algo sobre los motores?
amps? modelo? marca?
el quad vino sin ningún documento útil? no hay ningún manual ni nada?

gente, las compras se hacen hasta el miércoles a más tardar, y pagando un shipping de p#%a madre. Sino NO las puedo llevar.

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/23#issuecomment-3004527

## 

Rodrigo.

**Comment by mtailanian** [comment]
Si si dale para adelante!

Lo q dijo el pater es lo q habíamos hablado entre todos... así q estamos todos de acuerdo!
dale nomás!

**Comment by rlrosa** [comment]
compro 1 analyzador y 2 mongoose?

comentarios sobre motores/esc?

**Comment by spaternain** [comment]
2 mongoose???

Motores y ESC.... ni idea... alguno que sirva

**Comment by rlrosa** [comment]
On Mon, Dec 5, 2011 at 9:57 AM, spaternain
reply@reply.github.com
wrote:

> 2 mongoose???

sion compro 1 y si se rompe vemo como hace con el shipping de una d
repuesto, y paramos el proyecto por 1 mes o 2...

> Motores y ESC.... ni idea... alguno que sirva

d+!

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/23#issuecomment-3020394

## 

Rodrigo.

**Comment by spaternain** [comment]
Na dale... si te parece compramos 2 yo que se....

lo de los motores ya se que no es la gran descripción, pero ta.... en realidad no hay muchos requerimientos a priori

**Comment by rlrosa** [comment]
2011/12/5 spaternain
reply@reply.github.com:

> Na dale... si te parece compramos 2 yo que se....

compro 2, y tengo q pagar USD 30 de shipping xa asegurar q llegue.

> lo de los motores ya se que no es la gran descripción, pero ta.... en realidad no hay muchos requerimientos a priori

...

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/23#issuecomment-3020899

## 

Rodrigo.

**Comment by spaternain** [comment]
Ta... ni te quemes por los motores.... lo vemos con más tiempo después

**Comment by rlrosa** [comment]
pedi 2 mongoose, consegui 10% off por estudiante :), que en realidad
apenas compensa los USD 30 de shipping rapido.

2011/12/5 spaternain
reply@reply.github.com:

> Ta... ni te quemes por los motores.... lo vemos con más tiempo después
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/23#issuecomment-3021760

## 

Rodrigo.

**Comment by rlrosa** [comment]
por si me olvido de algo:
- x2 mongoose (en camino)
- analyzador lógico (en camino)
- IR emmiters + receivers (listo)
- Inversores (listo)
- x2 beagles sanas (1 lista, 1 en camino)
- un gyros, de onda (listo)
- x10 conectores (10 machos + 10 hembra) deans para la batería (en camino)
- soder wick (listo)
- MAX3373E (listo)

dps me compré un adaptador USB/serie q comparto durante el proyecto.

agiten si me olvidé de algo

**Comment by spaternain** [comment]
No me acuerdo de nada que falte.

Vamo a gozar

**Comment by rlrosa** [comment]
el fede volvió, trajo las mongoose :)
se ofreció a pasar por casa y dejarlas

si las quieren agiten, sino yo les entro dsp de las vac (11)

**Comment by mtailanian** [comment]
Listo!
