### ISSUE TITLE
caracterizacion motores con IR

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#24]
chicas hay plan aparte de "IR + photodiodos"?

creo que no es demasiado complejo el asunto, pero no se si hay alguna sutileza en el uso de estas cosas.
yo me llevo unas placas a la vuelta que tienen un dsp de Freescale, el  56F8013.

son breakout boards con montones de pines, tienen:
- GPIO
- ADC
- DAC
- botones
- USB para debugging
- UART

se programan en C desde un IDE de freescale, que capaz consigo (con capaz == taringa, etc). es facil hacer cosas faciles.

aplicacion inmediata seria:
- enchufar el led IR a uno de los GPIO, y el photodiodo al ADC.
- armar un programita que arranque a leer del ADC al apretar un boton y guarde el resultado en algun lado.
  - (lo mas choto seria correrlo con el debugger y verlo asi nomas
  - mas sofisticado seria mandarlo por UART y levantarlo en otro lado. esto no tiene SO, es arrancar casi de 0, o sea que todo es un poco complicado.

con esto creo que se podria resolver el tema de los motores.

estoy tratando de bajar a tierra los planes, para ver que nos va a hacer falta.
ejemplo: que haciamos con unos leds y unos photodiodos? no me parece muy feliz meter mano en la beagle si no es necesario...

**Comment by spaternain** [comment]
La posta de esto no era para medir solamente la velocidad angular con la que giran los motores??

Tipo poner una led de un lado de la helice, del otro lado el fotodiodo y medir con un frecuencimetro la frecuencia con la que se prende/apaga el diodo???

**Comment by rlrosa** [comment]
voy a averiguar como funcionana los leds
segun tengo entendido conduce cuando lo iluminan, y no conduce cuando no.

seria cuestion de armar un circuito que sature cuando hay corriente y
se muera  cuando no hay, y convierta a voltage.
eso lo mandamo al GPIO, e interrumpimos en cada flanco, llevando un contador N.
corremos un timer que pare cada T y se fije el valor de N.
de ahi podemos sacar la frecuencia.

creo q la placa tiene tipo 6 leds. podemos agregar alguno mas y hacer
un encoding medio grosero, asi podemos leer la frecuencia a ojo.
(chiche no+)

bueno, averiguo como funcan, y si es como pienso tonce ya queda.
capaz unos opamp con un schmitt xa para generar la onda cuadrada.
opamps hay en rondeau, asi que eso no seria problema.

2011/11/30 spaternain
reply@reply.github.com:

> La posta de esto no era para medir solamente la velocidad angular con la que giran los motores??
> 
> Tipo poner una led de un lado de la helice, del otro lado el fotodiodo y medir con un frecuencimetro la frecuencia con la que se prende/apaga el diodo???
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/24#issuecomment-2968096

## 

Rodrigo.

**Comment by spaternain** [comment]
Algo que convierta a tensión si pasa corriente. Un transistor pelado no andará? Y después derecho pal frecuencimetro... dejate de GPIOS. Esto era solo para la caracterización de los motores... Para saber a que velocidad gira si le escribo tal palabra I2C

**Comment by rlrosa** [comment]
no sabia que teniamos frecuencimetro
tonce esto queda resuelto.
