### ISSUE TITLE
verano!

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#25]
chicas

queria ver un poco cual es el plan, asi somos todos felices.

supongo que ya deben haber hablado d esto.
hay plan?
quienes tienen vacaciones?

a mi me gustaria arrancar el **lun 16 de enero**.
q dicen?

yo arranco a laburar ahi, solo 6hs por dia, o sea que me queda un buen rato cada dia.

en la cortita pensaba afanarles el gps cuando llego, y llevarmelo para arg, asi le meto al sw para eso.
tmb adaptar el imu_comm al mongoose, o sea que tengo xa divertirme.
igual en cba no creo que labura tanto...

**Comment by spaternain** [comment]
Mi plan era tomarme solamente desde el primero hasta el 10. Miercoles 11 estaría volviendo a Montevideo a meter huevo. Algún fin de semana puede ser sacrificado para irse pa fuera. 

Yo renuncié al laburo. A fin de año quedo libre de laburo. Así que estaré a full con el proyecto. Estoy esperando a ver si exoneré instalaciones así estoy más libre todavía. 

Llevate las cosas si para adaptarlas.

En principio hay tiempo hasta mayo para terminar todo. Por lo que leí del reglamento se puede hasta FIN DE JULIO.
Estamos muy atrasados. Hay que meter mucho más huevo.

Abrazos

**Comment by rlrosa** [comment]
el 11 parece razonable, el 12 tmb je

2011/12/6 spaternain
reply@reply.github.com:

> Mi plan era tomarme solamente desde el primero hasta el 10. Miercoles 11 estaría volviendo a Montevideo a meter huevo. Algún fin de semana puede ser sacrificado para irse pa fuera.
> 
> Yo renuncié al laburo. A fin de año quedo libre de laburo. Así que estaré a full con el proyecto. Estoy esperando a ver si exoneré instalaciones así estoy más libre todavía.
> 
> Llevate las cosas si para adaptarlas.
> 
> En principio hay tiempo hasta mayo para terminar todo. Por lo que leí del reglamento se puede hasta FIN DE JULIO.
> Estamos muy atrasados. Hay que meter mucho más huevo.
> 
> Abrazos
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/25#issuecomment-3035918

## 

Rodrigo.

**Comment by mtailanian** [comment]
Naaaaaa

No me digas q llegas y te vas a buenos aires????!!!

me tas jodiendo???

Yo también renuncié al laburo así q a partir del año q viene estoy todo para el proyecto.
y no pienso agarrar otro hasta terminar. Así le damos duro.

Yo me voy los primeros dias de enero y a más tardar el 15 ya estoy acá pa meterle.

**Comment by rlrosa** [comment]
2011/12/6 MatiTaila
reply@reply.github.com:

> Naaaaaa
> 
> No me digas q llegas y te vas a buenos aires????!!!
> 
> me tas jodiendo???

hace banda q no veo a la gente, y xa las fiestas siempre se juntan todos.
a mi me gustaria ir, supuse que en estas fechas no ibamos a estar
laburando mucho.
igual me llevo cosas, como dije en el primer mail.

vs mati pensabas meterle a full durante las fiestas?

> Yo también renuncié al laburo así q a partir del año q viene estoy todo para el proyecto.
> y no pienso agarrar otro hasta terminar. Así le damos duro.
> 
> Yo me voy los primeros dias de enero y a más tardar el 15 ya estoy acá pa meterle.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/25#issuecomment-3039087

## 

Rodrigo.

**Comment by mtailanian** [comment]
Primero q nada no me tomes el pelo.

Desde el 8 de diciembre al 23 tengo todo para el proyecto. y entre el 26 y el 30 tambien.

Me da hasta gracia q llegues y te vuelvas a ir. Me parece q t seguis cagando en nosotros y seguis siendo totalmente egoista. Más alla d q hagas cosas o no, la actitud me parece horrible. Dsp hablamos cuando vuelvas igual, si tenés tiempo

**Comment by rlrosa** [comment]
2011/12/6 MatiTaila
reply@reply.github.com:

> Primero q nada no me tomes el pelo.
> 
> Desde el 8 de diciembre al 23 tengo todo para el proyecto. y entre el 26 y el 30 tambien.
> 
> Me da hasta gracia q llegues y te vuelvas a ir. Me parece q t seguis cagando en nosotros y seguis siendo totalmente egoista. Más alla d q hagas cosas o no, la actitud me parece horrible. Dsp hablamos cuando vuelvas igual, si tenés tiempo

no hablo con uds hace rato, intento tantear cual es plan.
capaz habia un acuerdo de aflojarle a las obligaciones durante las
fiesta y dsp arrancar a full
si nos ibamos a tomar un rato durante las fiestas aprovechaba, sino no.

hay codigo como xa una semanita, entre el gps y la interfaz con la mongoose.
tiempo tengo, siempre hay tiempo. es cuestion de prioridades. yo me
pensaba irme a argentina, y llevarme el hw xa trabajar en eso. si uds
pensaban darle a full entonces le doy a full. para picar codigo es
irrelevante el lugar fisico, y estar alla significa que de noche,
cuando termino de trabajar, puedo pasar un par de horas con la flia,
en lugar de pasar el rato con mi vieja en casa.

creo q lo q + jode es que nada de lo que hice parece funcionar, por lo
menos no tuve noticias de que usaran algo con exito.
puede ser?

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/25#issuecomment-3039423

## 

Rodrigo.

**Comment by rlrosa** [comment]
si no me equivoco quedamos en que arrancamos con tuti el 11 de enero.
si me equivoco abran d nuevo, sino felices vacaciones! :)
