### ISSUE TITLE
I2C

### ISSUE THREAD

**Issue by spaternain** [rlrosa/uquad#26]
Gente,

Estuve jugando un ratito con el i2c tools.

El comando para escribir el valor 117 (por ejemplo) en el motor D0 (208) a priori sería

i2cset 2 208 A2 117 

Lo cual da el siguiente error
Error: Chip address out of range (0x03-0x77)!

En el .c del i2cset no encontré esta restricción si alguien se da cuenta por favor avisen

**Comment by rlrosa** [comment]
capaz quiere en hexa?

2012/1/15 spaternain
reply@reply.github.com:

> Gente,
> 
> Estuve jugando un ratito con el i2c tools.
> 
> El comando para escribir el valor 117 (por ejemplo) en el motor D0 (208) a priori sería
> 
> i2cset 2 208 A2 117
> 
> Lo cual da el siguiente error
> Error: Chip address out of range (0x03-0x77)!
> 
> En el .c del i2cset no encontré esta restricción si alguien se da cuenta por favor avisen
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/26

## 

Rodrigo.

**Comment by ghost** [comment]
Si la dirección es 0xD0 (11010000) entonces se precisan al menos 8 bits para direccionamiento.

I2C por defecto trabaja con 7 bits, entonces no le dan el rango para llegar a esa dirección y te da error de fuera de rango.

Es probable que el quad use direcciones de 8 bits o 10 bits. No creo que sean de 10 bits, es probable que esté usando direccionamiento de 8 bits, que en realidad no es un direccionamiento unicamente, sino que incluye indicación de lectura/escritura, por lo cual cada esclavo tendrá 2 direcciones de 8 bits que son traducibles en una única dirección de 7 bits.

El direccionamiento de 8 bits es igual al de 7 bits, sólo que incluye un bit de read/write al final.

Por ejemplo, si la dirección de mi esclavo es 1001 001 (0x49) entonces con el direccionamiento de 8 bits se usa:

1001 001 0 (0x92) para escribir (el último bit en 0 indica escritura)

1001 001 1 (0x93) para leer (el último bit en 1 indica lectura)

En nuestro caso las direcciones son 0xD0 (11010000), 0xD2 (11010010), 0xD4 (11010100) y 0xD6 (11010110), que son todas direcciones "para escribir", ya que terminan en 0. 

Entonces, para tener la dirección real de nuestro esclavo tenemos que truncar los valores anteriores y sacar ese cero final, ya que lo único que hace es indicarnos que esa es una dirección donde vamos a escribir y no leer. Si truncamos los valores de esta forma las direcciones reales de nuestros motores serían:

0xD0 (11010000) ----> 0x68 (1101000)
0xD2 (11010010) ----> 0x69 (1101001)
0xD4 (11010100) ----> 0x6A (1101010)
0xD6 (11010110) ----> 0x6B (1101011)

Estas direcciones son las direcciones reales en direccionamiento de 7 bits de los esclavos que tenemos nostros. Ahora si tenemos direcciones válidas para un direccionamiento en 7 bits.

El comando que habría que utilizar, por ejemplo, para escribir el valor 117 (0x75) en el motor 0xD0 (que en realidad es el motor 0x68) sería

i2cset 2 0x68 0xA2 0x75

No estoy seguro si es necesario pasarle todos los valores en hexadecimal, pero me parece que así entiende. Se puede probar, en todo caso, si convirtiendo esos valores a decimal el i2cset entiende igual que es lo que tiene que escribir y a dónde.

Fuente: http://www.totalphase.com/support/kb/10039/

**Comment by ghost** [comment]
Una sutileza nomás, en realidad 7 y 8 bits son lo mismo, depende si considerás si el bit de read/write es parte de la dirección o no.

En un caso tenés dirrección+read/write y en el otro tendrías una dirección para escribir y otra para leer, podrías pensar a cada esclavo como dos dispositivos diferentes, uno donde se lee y el otro donde se escribe.

Sutilezas aparte, el punto es que para tener la dirección del esclavo (la que hay que pasarle al i2cset) es necesario truncar el último bit de las direcciones que tenemos, tal como expliqué recién...

**Comment by spaternain** [comment]
Me gustó la explicación del matute... Además tiene más sentido que los nombres de las direcciones salten de a 1 y no de a 2.... pero ta....

Ahora probé lo siguiente:

i2cset 2 0x69 0xA2 117 
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will write to device file /dev/i2c-2, chip address 0x69, data address
0xa2, data 0x75, mode byte.
Continue? [Y/n] y

Error: Write failed

Voy a investigar un poco que puede etar pasando... pero parece andar bien.... capaz que le jode que nadie le de bola

**Comment by mtailanian** [comment]
Bien, rica explicación!!

Ahora cierra bastante más todo!!
Direcciones de motores consecutivas, todos con bit de escritura... Rico!

Pater probate eso ya!! je
necesito saber si anda!!
je

Bo, haganme acordar que agregue lo de las direcciones al informe del sniffer!!

Salute!!

**Comment by ghost** [comment]
Creo que te da Write Fail porque no hay ningún esclavo con esa dirección (no hay nada conectado, sólo el sniffer, que para los dispositivos conectados al bus es invisible, como buen sniffer que es), entonces no encuentra dónde escribir...

**Comment by ghost** [comment]
Al menos no agita nada de error de time-out. Creo que eso quiere decir que no necesitamos resistencias de pull-up externas. 

Igual hay que verificar eso. Habría que probar usarlo así como está y ver si encara.

Si da error de time-out hay que agregarle las resistencias externas y probar de nuevo...

**Comment by spaternain** [comment]
No hay chance de que se rompa algo si lo conectamos sin las resitencias de pull up??
El miercoles en la fing lo pruebo si quieren

**Comment by mtailanian** [comment]
Sabeloo! hay q probar eso!!! 

terrible leche! :P

**Comment by ghost** [comment]
Creo que no se rompe nada si lo conectamos sin resistencias de pull-up. El funcionamiento, según lo que estuve viendo, es así:

La Beagleboard asume que el nivel "natural" del bus es Vcc, por lo cual sólo se encargará de bajar dicho nivel a 0. La función de las resistencias de pull-up es, justamente, mantener el bus en Vcc cuando la Beagleboard no está haciendo nada.

Si hay resistencias de pull-up entonces la Beagleboard bajará el bus a cero, pero cuando lo suelte el mismo no subirá, por lo cual permanecerá abajo. Esto se traducirá, según tengo entendido, en un error de time-out. Entonces, si conectamos el i2c y no hay resistencias de pull-up activas simplemente tendremos un bus que está siempre bajo.

En caso de conectar resistencias de pull-up externas cuando ya existen pull-ups internos no estoy seguro si hay problema, a priori creo que no porque sería como tener dos resistencias de pull-up en paralelo. Por las dudas creo que lo mejor sería probar primero SIN resistencias de pull-up externas (esto es porque asumimos que existen pull-ups internos y están habilitados) y ver que pasa. Si eso nos da error de time-out entonces deberíamos agregar pull-ups externos y volver a probar.

**Comment by mtailanian** [comment]
Es un buen plan...
igual voy a buscar en la internes, alguien tiene q decir si la beagle trae resistencias o no....

de todas formas no creo q se rompa nada...

**Comment by ghost** [comment]
Yo busqué y no encotré nada concluyente, pero dale, capaz vos encontrás algo, dos boludos buscan mejor que uno... :P

Lo que si encontré es un montón de casos de gente que conectó la Beagleboard vieja SIN resistencias de pull-up y no rompió nada, sólo tuvo problemas de time-out. No veo porque debería ser diferente para la Beagleboard xM si no hay pull-ups internos habilitados. Si los hay tampoco creo que sea un gran problema. Igual, por las dudas, la posta es probar primero SIN pull-ups externos.

Acá hay un pibe que explica el error que le da y tira una explicación cortita de porque pasa eso que me convenció:
http://yetanotherhackersblog.wordpress.com/2011/04/07/interfacing-the-beagleboard-with-an-srf08-ultrasonic-ranger-over-i2c/

**Comment by rlrosa** [comment]
comento acá lo que quedó de hoy (le cambié el nombre al issue :) )

basicamente implementé lo que hizo el matute, pero en c.
no es gran cosa, no va con tuti
quedan tipo 150us entre cada MOTOR-REGISTRO-VALOR.

se veia en el osciloscopio, pero el quad no daba señales de vida...
puede q hay algún timeout, q si no le llega a todos los motores no hace nada, pero tmb puede ser q nos esté faltando una sequencia de arranque.

el código quedó en la SD de la beagle:
/home/root/work/
hay un README cortito.

para correrlo hacer:<pre><code>./cmd 50 50 50 50
</pre></code>
(cambiando los 50 por lo que quieras)

el codigo se puede editar con el nano, haciendo

<pre><code>nano nombre_del_archivo
</pre></code>

para compilar hacer:<pre><code>cd /home/root/work
make
</code></pre>

**Comment by mtailanian** [comment]
Bueno, ya que sabemos hablar i2c, me enorgulllezco de cerrar esta issue.

Si, domesticamos al Quad
