### ISSUE TITLE
switcheo - resolver compras

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#28]
# conversor RC a binario

como conversor de la señal del control a binario el matute encontró:
http://www.robotcombat.com/products/0-PL1210.html
http://www.robotcombat.com/products/0-PL752.html

faltaría un mux que sea  manejador por esa señal binaria.
# mux

http://www.nxp.com/documents/data_sheet/74LVC4066.pdf
http://search.digikey.com/us/en/products/74LVC4066D,118/568-8190-6-ND/2763168
parece poder alimentarse con 3.3v, y manejar la llave con hasta 5v. eso serviría para el hacer lo del i2c.
el modelo 14SO mide 8.75x4.0mm, o sea q no es tan chiquito.

si qusieramos agregar una señal xa la beagle quedan 2 canales libres, pero habría que ponerlo del lado lado 3.3 del shifter, y agregar canales al shifter, pero el MAX está lleno, no? (x2 de la uart y x2 del i2c)

capaz ta bueno mirar un poco más lo del switcheo antes de comprar.

**Comment by rlrosa** [comment]
La idea sería un mux alimentado a 3.3, y manejado por una señal (3.3) del receptor RC, tmb alimentado a 3.3
Esto iría dsp de la placa del mati, del lado que solamente hay 3.3.
son todas "breakout boards", así que no hay que soldar cosas con cuidado ni armar circuitos, pero es + grande. igual es chico.
El regulador es por si pinta comer de la beaglejuice en lugar de sacar de la mongoose.
- (U$S 6 c/u) Receptor RC: http://www.robotcombat.com/products/0-PL752.html
- (U$S 5 c/u) Mux (TS3A5017): http://www.sparkfun.com/products/8970
- (U$S 2 c/u) Regulador a 3.3: http://www.sparkfun.com/products/526

Hay solo 1 en stock del mux en sparkfun, estoy viendo si traen + y cuando.
si traen podríamos comprar esto y listo.

Son U$S 13 por kit + shipping.
Yo compraría 3 kits.
Shipping es ~U$S 5@sparkfun + otro tanto de los del RC.
Total serían U$S 50.

**Comment by mtailanian** [comment]
aim gibin an oquei

**Comment by mtailanian** [comment]
- Comprose
- Esperemos a que llegue para cerrar issue.
- Mail?

**Comment by rlrosa** [comment]
mandate mail a la gente del RC, decile q manden invoice con el envío y
que tenga el costo total (shipping inclusive)

On Thu, May 3, 2012 at 6:16 PM, MatiTaila
reply@reply.github.com
wrote:

> - Comprose
> - Esperemos a que llegue para cerrar issue.
> - Mail?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/28#issuecomment-5498673

## 

Rodrigo.

**Comment by mtailanian** [comment]
si, señor!

**Comment by mtailanian** [comment]
Matias,

I apologize for the inconvenience, but your package was dispatched from our facility yesterday. Unfortunately, it is too late for us to include a copy of the invoice inside of the package. However, I have included a PDF copy of the invoice for your records. I hope this helps you and I apologize for the inconvenience. Please let me know if there is anything else I can assist you with. 

Sincerely, 
Mandie Ferguson
CS Manager
The Robot MarketPlace
Phone: (941) 749-6030
Fax: (941) 753-5113
http://www.robotmarketplace.com/
"Like" us on Facebook!
www.facebook.com/RobotMarketPlace
