### ISSUE TITLE
Crítico - Falta de yerba

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#29]
Ya sabemos q hay q hacer cuando no hay yerba...
pri-con-pri!

**Comment by mtailanian** [comment]
si todos pusiéramos un granito de yerba....

yo traigo un kilito

(por las dudas: tengo el 2)

**Comment by rlrosa** [comment]
asd

**Comment by mtailanian** [comment]
trajwe

**Comment by rlrosa** [comment]
asd
