### ISSUE TITLE
theta

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#31]
- resolver el tema de que para un lado crece al doble/mitad, y para el otro anda bien.
- resolver la discontinuidad del atan -> acumular xa siempre?
- hacer que el control entienda que diff entre 0 y 2 grados es igual a la diff entre 0 y 358.

**Comment by mtailanian** [comment]
Discontinuidad del atan resuelta!!!

El control entiende!!! resuelto!!!

sobre el primer item: calibrar magneto dentro de Javi. Si anda ya se cierra!!!!!!!!

**Comment by rlrosa** [comment]
calib adentro de javi da + lindo, no da errores tan feos y asimétricos.
igual giros de 90 dan 70-100.

con los motores andando los errores dan muy parecido, o sea que el campo magn de los motores/cables/esc no molestan.

actualicé mag.mat, det_magneto y src/imu/imu_calib.txt

por ahora parece aceptable.
si seguimos viendo asquerosidades volvemos.
cambio y fuera!
