### ISSUE TITLE
delta altura no afecta

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#32]
- prueba con diff setpoints (1,2,3m) no afectan la performance. Ver si se corrije con el bias en el acc.

**Comment by mtailanian** [comment]
Pa mi lo que hay q hacer es 2 trayectorias distintas
    1 linea recta hacia arriba (2 o 3m)
    hovering

Capaz que lo q estamos intentando hacer no está del todo bien... y que por eso no nos da bola al poner diferentes alturas de setpoint...

**Comment by mtailanian** [comment]
Altura solucionada....
