### ISSUE TITLE
tito - arreglar

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#36]
- conseguir un taladro violento (mecha violenta) para reventar el tornillo sin bocha, ver si es cable roto o motor roto.
- si es motor, comprar otro, sino arreglar cable.
- armar esqueleto
- hacer cajita para tito
- pegarle el GPS en la mente
- placa para interconexión

**Comment by mtailanian** [comment]
### Avances 2012.05.03
- Taladro conseguido
- Cable arreglado
- Esqueleto armado
- Esc armado y funcionando

### Falta
- Placa interconexión + switcheo
- cajita?
- Cerebro?

**Comment by mtailanian** [comment]
Pa, si estará vieja esta issue que tito ya fue arreglado, testeado, ajustado y rompidoo!

chau, cerré esta issue!
