### ISSUE TITLE
Pruebas que no andan

### ISSUE THREAD

**Issue by spaternain** [rlrosa/uquad#38]
Estuve revisando con un poco más de cuidado la vida..... No se si es porque soy muy idiota o que, pero no me había dado cuenta de que poninendo los ruidos demenciales que tenemos en la lectura de los ángulos el simulador pira como loco. 

Creo que tenemos que trabajar en la linea de bajar un poco el ruido en la medida del ángulo o bajarlo en la estimación. 

Eso no más....

**Comment by rlrosa** [comment]
rico!

si querés jugar con promedios tocá en imu_comm.h
IMU_AVG_COUNT es la cantidad d muestras q se promedian.
tiene que ser menor a IMU_FRAME_BUFF_SIZE, pero podés aumentar
IMU_FRAME_BUFF_SIZE a gusto, no tranca nada.

el main siempre usa promedios (ahora usa promedios de 1, re loco él.)

2012/5/7 spaternain
reply@reply.github.com:

> Estuve revisando con un poco más de cuidado la vida..... No se si es porque soy muy idiota o que, pero no me había dado cuenta de que poninendo los ruidos demenciales que tenemos en la lectura de los ángulos el simulador pira como loco.
> 
> Creo que tenemos que trabajar en la linea de bajar un poco el ruido en la medida del ángulo o bajarlo en la estimación.
> 
> Eso no más....
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/38

## 

Rodrigo.
