### ISSUE TITLE
Compras junio

### ISSUE THREAD

**Issue by mtailanian** [rlrosa/uquad#39]
Después de escribir el mail me pareció bueno ponerlo en una issue, para que quede más ordenado....
- Sin disipador
  - Sandwiches
    - http://www.oomodel.com/lotus-t580-parts-t580z11-speed-controller-p-61766.html
    - http://www.moonhobby.com/lotus-t580-spare-parts-t580z11-speed-controller-p-61766.html
    - http://mymobilemms.com/OFFTHEGRIDWATER.CA/index.php?main_page=product_info&cPath=2_4&products_id=17 (creo q trae ambos)
  - Individuales
    - este q es upper: http://www.myrcmodel.com/index.php?main_page=product_info&cPath=1_2_110_108&products_id=2467&zenid=9fhcel4mdp75benqg459brajr5
    - Y la pareja (lower) es este otro http://www.myrcmodel.com/index.php?main_page=product_info&cPath=1_2_110_108&products_id=2468&zenid=9fhcel4mdp75benqg459brajr5
- Con disipador
  - Solo sandwiches
    - http://www.hobby-wing.com/t580-upper-esc.html
    - http://europemodels.eu/p_5430_Speed+Controller+Assembly+for+LOTUS+T580/
    - http://www.helipal.com/t580-z-11-speed-controller.html

Listo.

Solo recordar que lo que quedamos en comprar es:
- 1 sanwitch (1 de abajo y uno de arriba) con disipador
- 2 esc inferiores sin disipador
- 1 esc superior sin disipador

Obviamente van a ser en total 2 compras de 2 lugares distintos, porque no hay nadie que venda todo. Capaz lo que se puede hacer es pagar un shipping caro y otro barato. YO PREFIERO PAGAR LOS 2 CAROS. Si hay q elegir elegiria el que salga menos del limite para no pasar por aduana. Si los pasan sin tocar aduana, elegiría el q es igual al q tenemos, porque anda seguro. Pero insisto, quiero pagar los 2 shippings caros y de ser necesario pongo la diferencia entre shippings. ta?

Bueno vamo arriba q va a salir lindo viejoooo!!! 
que no decaiga!!! hay q seguir pasando bien! vamo arriba!!!!

Salú

**Comment by rlrosa** [comment]
yo compraría 3 sandwiches comunes por 250 shipping inc. abajo explico.

# ESCs v1

los q venden sandwich no venden sueltos, y comprar de a uno es 45+45 contra 75 el sandwich.

para hacer 3abajo+2arriba sería:
- 2sandwiches -> 75+75+25shipping
- 1 suelto        -> 45+20 shipping
  - Total: **235** (shipping inc)

si compramo refuerzos de bondiola:
- 3sandwiches -> 75*3+25shipping
  - Total: **250** (shipping inc)

yo iría por el triple bacon comprado acá http://mymobilemms.com/OFFTHEGRIDWATER.CA/index.php?main_page=product_info&cPath=2_4&products_id=17
que dicen tener stock (28) y son canadienses q compran d china, capaz mandan más rápido.
ya mandé mail, mñna voy a agitar x skype (no están ahora)

# ESCs v2

del sandwich con pan integral, hobby-wing no tiene stock, europemodels manda solo a europa (dsp de romperte las bolas abundante) y helipal no manda a uruguay (a arg si...)
estuve viendo un poco en [este post de RC groups](http://www.rcgroups.com/forums/showthread.php?t=1661154) pero no encontré nada cheto. los bueno es esto:

<pre><code>1. All old ESCs can be sent back to your distributors for a free exchange to the new version, but you need to pay for the return shipping fee (both way).In return, you will get one pair of props (either color of your choice) free as a token of appreciation of your support on T580.
2. A gift to all the new purchase of T580: two pair of props:a orange pair and a black pair.
3. A gift to all the new purchase of the new ESC: a pair of props with your choice of color. 
</code></pre>


capaz si les mandamos todo quemado nos regalan algo...

los chinos tienen el [ESC 2.0](http://www.himodel.com/helicopters/Speed_Controller_Assembly_for_LOTUSRC_T580_T580P_New_Protocol.html#) en back order, y explícitamente dicen que no anda con el  [cerebro 1.x](http://www.himodel.com/helicopters/Fly_Control_PCB_Board_Main_Board_for_LOTUSRC_T580_Quadcopter_Old_Protocol.html) que aparentemente es el nuestro. capaz hay q meter mano con el sniffer d nuevo, capaz no... a esta altura diría _seguro q hay q meter mano y cambiar el kernel por algo y arreglar la heladera del IIE o algo del estilo_.

**Comment by mtailanian** [comment]
ta por mi esta bien!
y me gusto lo de arreglar la heladera!! :P

si parece q los v2 no andan, ni compramo.... yo lo que lei por ahi es que decian q era para el "nuevo protocolo", y enfatizaban q no va a andar para el "viejo protocolo". No se a q se refieren con eso del protocolo... pero bue... por las dudas...

en fin, pa mi esta bien la compra...

**Comment by rlrosa** [comment]
tracking:
- motor: LN297300394US
- himodel: [fedex](http://fedex.com/Tracking?ascend_header=1&clienttype=dotcom&cntry_code=us&language=english&tracknumbers=876732176502)
- goodluckbuy: no hay tracking todavía

**Comment by rlrosa** [comment]
de las compras himodel llegó y goodluckbuy devolvió la $.
queda el motor, que supongo q estará clavado en la aduana desde hace siglos.
mñna llamo al correo a ver q tienen xa decir.

**Comment by rlrosa** [comment]
el correo hace casi 2 meses q tiene todo trancado en el aeropuerto jej
dsp veo q onda con el fakin motor

**Comment by rlrosa** [comment]
ya fue, no?
