### ISSUE TITLE
Fiestaa!!

### ISSUE THREAD

**Issue by mtailanian** [rlrosa/uquad#41]
Lo mas urgente es ver lo de la musica y lo de los barriles de cerveza

Rodrigo, vos habias dicho algo de q conocias a alguien q tenia luces y musica o pire?

barril digo de pegar el del pater, la cerveza artesanal y si quieren otro de pilsen/patricia

**Comment by rlrosa** [comment]
q buen issue!!

"pablo" (me lo recomendó una amiga de mi vieja q organizo eventos y blabla) nos cobra:
- 2000 por amplificación, luces + máquina de humo.
- 2800 por lo anterior, + laser + bolas espejos + no se q cositas más onda "yo me encargo d q esté gozado" y por ir el y encargarse de todo toda la noche.

yo voto por el 2800, si se rompe algo el tipo está ahí, q se maneje para q no le rompan las cosas.
se encarga de pasar la música, de no se desenchufe nada, n se, pa mi pinta desentenderse y no es tanta $
dice q pendrive con "lo q no puede faltar", supongo q quiso decir agapornis. si la embola le decimo q queremos pasar música nosotros y listo, lo hacemo armar y desarmar jej

son 1/2 de seña, y hay q irlo a buscar y llevarlo d vuelta, vive por la aguada: castillos 2255 apto 1
dijo q podemos retirar las cosas el 2 si pinta, pero pa mi pinta buscarlo de una y ya era
llevar posa cosas xa que los equipos no estén en el piso, etc.

suena todo muy rico, si no fuese xq me lo recomendaron diría q es un chanta, pero como lo recomienda alguien q trabaja de esto ta gozado :)

agité por el barril y me dieron mal el número, me pasaron el de alguien q me respondió: "equivocado", y dsp "cualquier cosa avisá" XD
sigo averiguando

**Comment by mtailanian** [comment]
pa gozado ese pibee

pa mi pinta el 2800 pero pedirle q nos deje meter mano c la musica
vamos a buscar las cosas el 2, lo lo llevo, armamo todo, cargamo todo lo q haya q cargar 
pero a la vuelta le pagamo el taxi, ni en pedo manejo en pedo
je

otra cosa, capaz q es mejor llevar las cosas el 3 mismo porque no hay puerta y se pueden robar todo....
si, sin duda. el 3

barril seguimo averiguando, pater dijo q iba a averiguar por el otro
podemos pegar los 2

lo de la musica y luces pa mi ya confirmale! es exelente y no muy caro

Dema!!!

q rico q va a estar esoooo

**Comment by rlrosa** [comment]
sabelo ahora le confirmo y le arrimo la plata durante el finde xa moverme un poquete.

sobre el fb, yo había armado algo para pner el evento en fb, pero no quedé muy feliz jej
armé esto:

<pre><code>
se terminó!!! :D
parece q infinito no era taaaan largo

# defensa
defendemos el proyecto el lunes 30 de julio a las 17:30 en la FING, salón a definir.
los que quieran ir a escuchar y hacer preguntas molestas están invitados, y los q quieran ir a usarnos para mezclar ingredientes de torta tmb

# FIESTA
la parte más interesante, VIERNES 3 DE AGOSTO se arma fiesta en la casa del pater!
nosotros ponemos una buena base de chupe, lleven lo q quieran para completar!

ns vemo la semana q viene!
atte,
pater,mati,rela
</code></pre>


fb te pide:
- fecha - pensaba poner la fiesta, y más en chico la defensa
- lugar
- visibilidad (amigos, solo invitados, todo el mundo) -> con el pater dijoms de poner amigos, así no hay q andar invitando a mano
- descripción - lo q quise armar
- foto - pensaba poner una de la cancha del otro dia, q sale con buena luz y tamo con tito, y dsp de la defensa cambiarla por una foto hechos mierda

ponemos onda lluvia? tipo lo q puse o algo más onda "lleven chupe"

**Comment by rlrosa** [comment]
ya reservé, el finde le pago la seña.
dice q no alcanza con auto (menos con taxi) xa llevar las cosas, dijo q onda fiorino o camioneta abierta.
mi primo tiene un camionetón, chev viejazo. creo q anda bien. averiguo, igual xa la vuelta no le tengo fe jej
capaz mejor un flete y ya era, así no jodemos a nadie.

**Comment by mtailanian** [comment]
Bien! gozada esa reserva

el flete por lo general es caro, pero vale la pena
creo q lo mejor es conseguir prestada una camioneta o algo asi para la ida y contratar un flete pa la vuelta... les parece?

lo del fb esta bien! q es lo q no te conforma?

Va a estar gozado!!

**Comment by rlrosa** [comment]
q rico estar planeando esto :D

en realidad quería q leyeran lo del fb antes de publicarlo :)
publico? creo q no tengo la foto acá, mati vs te bajaste las fotos de
la cam o te llevaste la cam?

podemos agitar en el evento a ver si alguien se ofrece a poner
camioneta, y mientras pensamo a ver si conocemo gente

On Fri, Jul 20, 2012 at 8:40 PM, MatiTaila
reply@reply.github.com
wrote:

> Bien! gozada esa reserva
> 
> el flete por lo general es caro, pero vale la pena
> creo q lo mejor es conseguir prestada una camioneta o algo asi para la ida y contratar un flete pa la vuelta... les parece?
> 
> lo del fb esta bien! q es lo q no te conforma?
> 
> Va a estar gozado!!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/41#issuecomment-7147491

## 

Rodrigo.

**Comment by spaternain** [comment]
Bo.. no me están llegando los mails de esto. Publicá el evento YA.

El barril de Pilsen está reservado. Lo llevan el viernes después de las 14hs. Estoy viendo lo de Davok.

**Comment by rlrosa** [comment]
rico! birra!

el evento en fb está https://www.facebook.com/events/426119034105374/
la foto con tito va mñna

la música la señé!
el tipo tiene flete ida+vuelta por 600, nos desentendemos del todo
voy a ver q precios manejan x ahí, pero siendo algo de cargar cosas y a las 8 de la matina, yo q se, 600 no me parece mal (taxi hasta la aguada sería 2x150+ creo, lo calculé siguiendo un taxi en la bici)

**Comment by rlrosa** [comment]
otro éxito.
