### ISSUE TITLE
hakas

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#42]
yo x ahora me anoto:
- la parte de costos
  - agregar q usamos osciloscopio, sniffer, etc
  - meter algo de elección de hardware
- emprolijar el GPS (va a quedar + largo)

**Comment by rlrosa** [comment]
ta.

**Comment by rlrosa** [comment]
quedan las cositas de colores (si pinta) y los detalles x todos lados

**Comment by mtailanian** [comment]
subi un monton de cosas
la gran mayoria son pelotudeces que tenia guardadas por ahi y las puse en el repo para que no se pierdan

hice el diagramita de kalman en ingles para el paper, esta en latex/paper/pics_paper o algo asi

subi un monton de cosas que habiamos escrito alguna vez sobre la comparacion de las plataformas por si quiciéramos agregar algo. Por ejemplo hay tablitas comparando sensores y placas pensantes (gumstix vs beagle)

En la parte de costos vi que rodrigo agrego lo de la comparacion de hardware; no pinta hacer un anexo aparte para eso? Y lo otro que quiero comentar de esa parte para no olvidarme, es poner el mega microscopio en la parte de costos ocultos

Tengo unas cuantos nucleos de la beagle que estaria bueno dejarlos a mano para el que lo quiera usar... les parece si lo subo aca?

Capaz q tendríamos que juntarnos 1 vez antes del lunes? o les parece pilotearlo por mail?

Salute!

**Comment by spaternain** [comment]
Acomodé todas las boludeces hasta el sniffeo (a la vuelta en el bondi sigo). Además arregle el tema de tabla/cuadro. 
Ahora las tablas dicen tabla en vez de cuadro. 

No me pinto darle bola cuando lloró que torque, momento, bla y que usaramos una. 
Cosas que me saltee:
- imágen de las fases (linea al aire)
- lo de despreciable... bla
- snifeo: Hakas pregunta de donde sacamos el chrono VU. se pone algo ahí?
- Imagen del snifeo que no se leia sigue sin leerse
- lo de rudder/ruddle, por ahora lo dejé. Me parece que hakas tiene razón. Ustedes que dicen?
- color amarillo de las gráficas
- las gráficas del msp430 no le habían gustado. Estaban mal los ejes y habria que explicar algo.

Cosas con las que no quede conforme como quedaron escritas:
- último parrafo de la subsection tiempo discreto en el simulador. Hakas había agitado algo de la cota superior.

**Comment by spaternain** [comment]
Juntarnos podría esar bien.

2 cosas más que habíamos agregado:
- GPS mejor cuando andamos rápido
- Micro embebido en la conclusión

**Comment by rlrosa** [comment]
rico!
no se si pinta juntarnos, creo q se rema bien x mail, pero como quieran.
horarios:
hoy de 18:30-19:45
mñna antes de 12 o a las 18 hasta 19
sino domingo de noche (vie me voy xa floresta hasta dom)

**Comment by spaternain** [comment]
Hoy no puedo yo.... Hubo paro de funcionarios en el cure y tuve que
arrancar la clase más tarde (a la 1). Salgo 3 y poco de acá, llegaré como a
las 6 y media calculo a xxx. No da mucho el rato. Mañana de mañana puedo.

**Comment by rlrosa** [comment]
> subi un monton de cosas que habiamos escrito alguna vez sobre la comparacion de las plataformas por si quiciéramos agregar algo. Por ejemplo hay tablitas comparando sensores y placas pensantes (gumstix vs beagle)

a mi no me pintó poner demasiado xq no me pinta mucho ponerle demasiado. las tablitas que vi en eleccion_hardware son de cosas q al final no les dimos bola (micro, ram, etc son medio q lo mismo gumstix-beagle). puse chiquito q elegimos la beagle xq era más barata - 150, la gumstix era 220 + la placa extra xa tener puertos usb etc (50).
sobre las specs de los sensores tampoco puse mucho, puse q elejimos la que tenía más sensores, los sensores eran medio q todo lo mismo (excepto q la mongoose tiene digitales mientras q otras tienen analógicos, pero ta. podría agregar algo d eso)

> En la parte de costos vi que rodrigo agrego lo de la comparacion de hardware; no pinta hacer un anexo aparte para eso? Y lo otro que quiero comentar de esa parte para no olvidarme, es poner el mega microscopio en la parte de costos ocultos

puse "soldadores para SMD", como costo oculto, agrego q tiene microscopio.

> Tengo unas cuantos nucleos de la beagle que estaria bueno dejarlos a mano para el que lo quiera usar... les parece si lo subo aca?

creo q esas cosas son GB capaz, dsp va a querer bajar a la beagle... (comprimido, pero bajar en fin)
yo los pondría en dvds

en un rato yo acomodo esto:

> imágen de las fases (linea al aire)
> lo de despreciable... bla
> snifeo: Hakas pregunta de donde sacamos el chrono VU. se pone algo ahí?
> GPS mejor cuando andamos rápido
> Micro embebido en la conclusión
> de donde sacamos el chrono VU. se pone algo ahí?

**Comment by spaternain** [comment]
Ahora si, arregle todas las boludeces. Además de lo que mandé más temprano
queda:

Quedaron todos los decimales con coma. Las figuras con punto por ahora.
Supongo que cambiando un comando se puede dejar todo con puntos.

Sniffer:
    - Numerar las pruebas arrancando por el 1.

Motores:
    - Lo del Trise me dejó mal. Si el transitorio es de 0.2 segundos
tenemos un problema serio, ya que vamos a hacer acciones de control cada
0.01 segundos. Que hacemos con esto?

GPS:
     - Figura 10.12: El caption ta muy pegado al título. No pude arreglarlo.

Kalman:
    - Gráficas que tienen mal las unidades del eje horizontal.

**Comment by spaternain** [comment]
Lo de numerar las pruebas lo hacemos? o ya era?

**Comment by spaternain** [comment]
Agregué lo de los recursos humanos. Me embol\'o poner el gantt. Fijesense
si les gusta y completen la tabla con lo que falta.

**Comment by rlrosa** [comment]
costos me re emboló, acepto lo q sea q pusiste.
cual era la parte de control q querías q leyeramos d vuelta?

**Comment by mtailanian** [comment]
yo lo q quedamos hoy lo subi ya...

**Comment by spaternain** [comment]
No se, no me acuerdo ya. Falta ver que hacemos con el trise

2012/8/11 MatiTaila notifications@github.com

**Comment by rlrosa** [comment]
pater el mati te explicó como usar procesar los datos con los scripts?

podemos encararlo nosotros mñna a las 9, así q las 10 el mati sale de audio
y se puede llevar el main compilado para el local q imprime.

On Sat, Aug 11, 2012 at 4:43 PM, spaternain notifications@github.comwrote:

> No se, no me acuerdo ya. Falta ver que hacemos con el trise
> 
> 2012/8/11 MatiTaila notifications@github.com
> 
> > yo lo q quedamos hoy lo subi ya...
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/rlrosa/uquad/issues/42#issuecomment-7663788>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rlrosa/uquad/issues/42#issuecomment-7669593.

## 

Rodrigo.

**Comment by spaternain** [comment]
yo tengo clase mañana de 8:15 a 9:45. Después de eso no tengo drama

2012/8/12 Rodrigo L. Rosa notifications@github.com

> pater el mati te explicó como usar procesar los datos con los scripts?
> 
> podemos encararlo nosotros mñna a las 9, así q las 10 el mati sale de
> audio
> y se puede llevar el main compilado para el local q imprime.
>

**Comment by mtailanian** [comment]
saque lo de la respuesta al escalon de los motores y subi esa versión al moodle...
la subi en uquad, para tener una liviana a mano...

encontre una referencia que estaba con ??, creo q el resto estaría todo... igual si encuentran algo para arreglar se puede volver a subir...
