### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by spaternain** [rlrosa/uquad#44]
Algunas cosas del paper que me parece habría que corregir:

II. Model of Quadrotor
    - todos los motores giran clockwise
    - No se dice que es M. Los torques de la figura son opuestos a la vel angular.
    - Al principio de la página 2 dice S_i tendria que ser S_I
    - Yo diria que x,y,z es la posición del centro de masa del sistema expresada en el sistema inercial
    - v_q son relativas al sistema del cuadricóptero.

III. Sensores:
    - Agregaría la formula con la que se calculan los ángulos de Euler.
    GPS: 
    -"tens of meters y a couple of seconds" Esto esta bien? esa y me resulta dudosa.
    - No me gusta decir que el GPS tiene una exactitud de 2-3 metros y que la datasheet diga 5m CEP. Podemos ocultar el dato de la datasheet.

V. Control design.
    - Pondría la imágen con colores
    - Agregaría que las trayectorias circulares solo pueden ser en torno al eje vertical.
    - Agregaría la ecuación de Ricatti (también a la doc)
    - Decir que controlabilidad y observabilidad aseguran la estabilidad

VI. Software
    - Decir que el control que se implementó es discreto y que hubo que discretizar el modelo y utilizar una versión discreta de LQR. 

VII. Results
    B. System response
    - Se habla primero de la figura 6 y después de la 5. queda mejor al revez. 
    - Pondría la imagen que usamos para la defensa para el ángulo de roll, tenía mucho menos sobretiro.

Comentario general: Me gusto mucho. Capaz que estaba lindo poner una foto de tito y de la beagle. Pero ta, no es necesario.

**Comment by rlrosa** [comment]
ta
