### ISSUE TITLE
Documentación de los Hitos

### ISSUE THREAD

**Issue by ghost** [rlrosa/uquad#6]
No quise poner la documentación de los hitos en la carpeta de latex para no armar confusión con el main, después de todo las presentaciones no van a ir en la documentación final...

Para eso cree otra carpeta llamada "presentaciones_hitos" en la raíz del directorio...

Les gusta así? Si a alguien se le ocurre algo mejor que agite y vemos...

**Comment by rlrosa** [comment]
ai agri.
