### ISSUE TITLE
build sys - cmake Vs scons Vs ...?

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#7]
chicas!

alguien sabe algo de scons o cmake?
si a nadie le importa tonce leo y elijo cual usar
te hacen la vida más fácil a la hora de compilar cosas gordas.
creo que está bueno armar un código que sea razonablemente manejable a medida que se ponga gordo y puto.

yo por mi me asigno a esto.
dsp de armar una estructura razonable podemos agregar cosas sin romper todo, y garantizar que a todos les compile, etc. eso en gral es feliz

**Comment by mtailanian** [comment]
Acá el q está más metido en eso sos vos... Lo que leí por ahí es que esos 2 son los mejores. Lo bueno del SCons es q es en python y suele ser amigable... pero no se...

**Comment by rlrosa** [comment]
lo hice con cmake, quedó fácil :)
