### ISSUE TITLE
entrega doc

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#8]
propongo cama redonda con la doc que vamos  a entregar, así vemos cosas raras en cosas ajenas.

vamos a entregar todo lo que está en /latex o eso lo vamos armando y solo se entrega al final?

**Comment by mtailanian** [comment]
Cama redonda es tipo mesa redonda pero cama?
no te entiendo a veces guachín...

Vamos a entregar todo lo q está en /latex si (menos plan_proy obviamente)

**Comment by rlrosa** [comment]
On Sun, Sep 18, 2011 at 6:03 PM, MatiTaila
reply@reply.github.com
wrote:

> Cama redonda es tipo mesa redonda pero cama?
> no te entiendo a veces guachín...

me pasa seguido, no te preocupes
digo de leer lo que otros hicieron, así vemo cagadas ajenas.

> Vamos a entregar todo lo q está en /latex si (menos plan_proy obviamente)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/8#issuecomment-2129520

## 

Rodrigo.

**Comment by mtailanian** [comment]
Si yo le di a fondo al Modelo teórico q estaba pesadito. Básicamente lo hice de nuevo y dsp comparé resultados... Creo q está 10 puntos. Ahora voy a explicar más algunas cosas que fueron las que más me costaron a mi y queda rico! 
La elección de hardware ya pasó una inspección cuando la terminamos, eso tmb estaría
Lo que quedaría por revisar es lo q escribiste vos. Ahora le meto a eso.

Salute!

**Comment by rlrosa** [comment]
ok, yo tengo pendiente leer el modelo (lease, no tengo npi sobre eso je)

2011/9/18 MatiTaila
reply@reply.github.com:

> Si yo le di a fondo al Modelo teórico q estaba pesadito. Básicamente lo hice de nuevo y dsp comparé resultados... Creo q está 10 puntos. Ahora voy a explicar más algunas cosas que fueron las que más me costaron a mi y queda rico!
> La elección de hardware ya pasó una inspección cuando la terminamos, eso tmb estaría
> Lo que quedaría por revisar es lo q escribiste vos. Ahora le meto a eso.
> 
> Salute!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/8#issuecomment-2129553

## 

Rodrigo.

**Comment by mtailanian** [comment]
Ta igual capaz q no vale la pena que te metas en eso.
Vos ves.
Pero yo lo revisé con mucho cuidado....

**Comment by rlrosa** [comment]
creo que ya fue esto
