### ISSUE TITLE
beagleboard wifi

### ISSUE THREAD

**Issue by rlrosa** [rlrosa/uquad#9]
mandé mail a los de liquidware.
todo la página parece indicar que ellos usan y dan soporte al beagle rev C4, no al XM.
no debería ser problema, ya que es más o menos igual, pero hay algunas diferencias (el XM no tiene nand flash, por ejemplo)
capazq alguna cosa de esas hace que no arranque

dsp me cuentan bien q pasa
si ven palitos y caramelos en el puerto serie puede ser que tengas un baudrate distinto al que setean ellos. deberían ser palitos y caramelos de muchos sabores. si son todos del mismo gusto entonces hay algo muy raro...
yo siempre usé 115200 y anduvo bien. eso se setea desde consola haciendo
habría que ver bien donde se configura eso en el kernel
dsp que tienen un linux andando, el baudrate se setea haciendo
stty -F /dev/ttyUSB0 115200

no deberías necesitar sudo

siguieron esto:
http://antipastohw.pbworks.com/w/page/27990127/Wi-Fi%20Setup%20Using%20Belkin%20F5D7050%20USB

usando una SD con las instrucciones de 
http://antipastohw.pbworks.com/w/page/27960896/Liquidware%20BeagleBoard%20Linux%20Kernel
?

hicieron todo eso?
parece un embole...

le hice diff a la conf que usan ellos
https://files.pbworks.com/download/MTE39lLPow/antipastohw/27969009/.config
y a la que uso yo, y hay muchas cosas distintas. no se cuales importan y cuales no.
yo lo que puedo hacer es compilarme uno con la cfg de ellos, y ver si anda.
no voy a poder probar el wifi jej pero puedo ver si anda el PWM, y si anda el beagle en gral

salú

**Comment by mtailanian** [comment]
Nuuuu..... en uno de los links que te pasé hay un link para descargar 2 .tar: 1 pal boot y otro pal Angstrom

Uso eso y no butea...

Capaz q habría q probar cocinar nuestro propio kernel no?

**Comment by rlrosa** [comment]
hoy de noche puedo poner eso a andar. lo pruebo y te mando lo que salga

2011/9/19 MatiTaila
reply@reply.github.com:

> Nuuuu..... en uno de los links que te pasé hay un link para descargar 2 .tar: 1 pal boot y otro pal Angstrom
> 
> Uso eso y no butea...
> 
> Capaz q habría q probar cocinar nuestro propio kernel no?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlrosa/uquad/issues/9#issuecomment-2133305

## 

Rodrigo.

**Comment by rlrosa** [comment]
el horno se rompió d nuevo...
la receta de liquidware la puse en lugar de la que usaba xa el beagle, hay un montón de diffs, por ejemplo  la del beagle es xa 2.6.32, y la de liquidware xa 2.6.35-rc4. no se si el sistema que describe la wiki se banca un kernel tan nuevo.

tengo que ver con más detalle en q la caga, a ver si se puede arreglar, o ver como arrancar una conf que use esa receta de una.
dsp lo veo...

**Comment by mtailanian** [comment]
Listo el pollo. O el WiFi...
